/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.master;

/**
 *
 * @author ARCH
 */
public class Pelanggan extends javax.swing.JPanel {

    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblanggota = new javax.swing.JTable();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        falamat1 = new javax.swing.JTextField();
        label9 = new usu.widget.Label();
        panelGlass10 = new usu.widget.glass.PanelGlass();
        falamat4 = new javax.swing.JTextField();
        label7 = new usu.widget.Label();
        panelGlass11 = new usu.widget.glass.PanelGlass();
        falamat5 = new javax.swing.JTextField();
        label10 = new usu.widget.Label();
        panelGlass12 = new usu.widget.glass.PanelGlass();
        falamat6 = new javax.swing.JTextField();
        label11 = new usu.widget.Label();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        label1 = new usu.widget.Label();
        err_msg = new usu.widget.glass.PanelGlass();
        lblPesan = new usu.widget.Label();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        btnDel1 = new usu.widget.ButtonGlass();
        btnEdit = new usu.widget.ButtonGlass();
        btnAdd = new usu.widget.ButtonGlass();
        btnRefresh = new usu.widget.ButtonGlass();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        btnSearch = new usu.widget.ButtonGlass();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(1366, 650));

        tblanggota.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        tblanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "No Anggota", "Nama Anggota", "TTL", "Jenis Kelamin", "Alamat", "No.Telpon", "Simp. Pokok", "Tgl Masuk", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblanggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblanggota);

        panelGlass5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass5.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass5.setRound(false);

        panelGlass7.setAlpha(1.0F);
        panelGlass7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass7.setRound(false);

        falamat1.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        falamat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label9.setBackground(new java.awt.Color(255, 255, 255));
        label9.setText("Id. Pelanggan");
        label9.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass7Layout = new javax.swing.GroupLayout(panelGlass7);
        panelGlass7.setLayout(panelGlass7Layout);
        panelGlass7Layout.setHorizontalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(falamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass7Layout.setVerticalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGlass7Layout.createSequentialGroup()
                .addGroup(panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(falamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelGlass10.setAlpha(1.0F);
        panelGlass10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass10.setRound(false);

        falamat4.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        falamat4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label7.setBackground(new java.awt.Color(255, 255, 255));
        label7.setText("Nama");
        label7.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass10Layout = new javax.swing.GroupLayout(panelGlass10);
        panelGlass10.setLayout(panelGlass10Layout);
        panelGlass10Layout.setHorizontalGroup(
            panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(falamat4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass10Layout.setVerticalGroup(
            panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass10Layout.createSequentialGroup()
                .addGroup(panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(falamat4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelGlass11.setAlpha(1.0F);
        panelGlass11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass11.setRound(false);

        falamat5.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        falamat5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label10.setBackground(new java.awt.Color(255, 255, 255));
        label10.setText("Alamat");
        label10.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass11Layout = new javax.swing.GroupLayout(panelGlass11);
        panelGlass11.setLayout(panelGlass11Layout);
        panelGlass11Layout.setHorizontalGroup(
            panelGlass11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(falamat5, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass11Layout.setVerticalGroup(
            panelGlass11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass11Layout.createSequentialGroup()
                .addGroup(panelGlass11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(falamat5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelGlass12.setAlpha(1.0F);
        panelGlass12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass12.setRound(false);

        falamat6.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        falamat6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label11.setBackground(new java.awt.Color(255, 255, 255));
        label11.setText("No.Telp");
        label11.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass12Layout = new javax.swing.GroupLayout(panelGlass12);
        panelGlass12.setLayout(panelGlass12Layout);
        panelGlass12Layout.setHorizontalGroup(
            panelGlass12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(falamat6, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass12Layout.setVerticalGroup(
            panelGlass12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass12Layout.createSequentialGroup()
                .addGroup(panelGlass12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(falamat6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelGlass5Layout = new javax.swing.GroupLayout(panelGlass5);
        panelGlass5.setLayout(panelGlass5Layout);
        panelGlass5Layout.setHorizontalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass5Layout.createSequentialGroup()
                        .addComponent(panelGlass7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(panelGlass5Layout.createSequentialGroup()
                        .addGroup(panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelGlass12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelGlass5Layout.setVerticalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass4.setAlpha(0.0F);
        panelGlass4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        panelGlass4.setPreferredSize(new java.awt.Dimension(264, 54));
        panelGlass4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("DATA PELANGGAN");
        label1.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        panelGlass4.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 30));

        err_msg.setRound(false);

        lblPesan.setForeground(new java.awt.Color(255, 255, 255));
        lblPesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesan.setFont(new java.awt.Font("Meiryo UI", 0, 10)); // NOI18N

        javax.swing.GroupLayout err_msgLayout = new javax.swing.GroupLayout(err_msg);
        err_msg.setLayout(err_msgLayout);
        err_msgLayout.setHorizontalGroup(
            err_msgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(err_msgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        err_msgLayout.setVerticalGroup(
            err_msgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        panelGlass6.setAlpha(0.0F);
        panelGlass6.setRound(false);

        btnDel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_delete.png"))); // NOI18N
        btnDel1.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnDel1.setPreferredSize(new java.awt.Dimension(117, 41));
        btnDel1.setRoundRect(true);
        btnDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDel1ActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_edit.png"))); // NOI18N
        btnEdit.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(117, 41));
        btnEdit.setRoundRect(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_new.png"))); // NOI18N
        btnAdd.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnAdd.setRoundRect(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_refresh.png"))); // NOI18N
        btnRefresh.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(117, 41));
        btnRefresh.setRoundRect(true);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        panelGlass2.setAlpha(1.0F);
        panelGlass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass2.setRound(false);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btn_search.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass2Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelGlass6Layout = new javax.swing.GroupLayout(panelGlass6);
        panelGlass6.setLayout(panelGlass6Layout);
        panelGlass6Layout.setHorizontalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass6Layout.setVerticalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(err_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelGlass5, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 521, Short.MAX_VALUE)
                        .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(panelGlass6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(err_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelGlass5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblanggotaMouseClicked
        //        // TODO add your handling code here:
        //        fno.setText(String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 0)));
        //        fnama.setText(String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 1)));
        //        ftempat.setText(String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 2)));
        //        String dateValue = String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 3));
        //        java.util.Date date=null;
        //        try{
            //            date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
            //        }catch(ParseException ex){
            //            System.out.println(ex);
            //        }
        //        jdatebirth.setDate(date);
        //        falamat.setText(String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 5)));
        //        ftelpon.setText(String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 6)));
        //        fsimpkok.setText(String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 7)));
        //        String dValue = String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 8));
        //        java.util.Date ddate=null;
        //        try{
            //            ddate = new SimpleDateFormat("yyyy-MM-dd").parse(dValue);
            //        }catch(ParseException ex){
            //            System.out.println(ex);
            //        }
        //        jdatemasuk.setDate(ddate);
        //        boxstatus.setSelectedItem(String.valueOf(tblanggota.getValueAt(tblanggota.getSelectedRow(), 9)));
    }//GEN-LAST:event_tblanggotaMouseClicked

    private void btnDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDel1ActionPerformed
        // TODO add your handling code here:
        //        try{
            //            String id=String.valueOf(tblpengguna.getValueAt(tblpengguna.getSelectedRow(), 0));
            //            if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                //                con.queryDelete("tb_pengguna", "NoAnggota="+id);
                //                clear();
                //            }else{
                //                return;
                //            }
            //        }catch(Exception e){
            //            System.out.println(e);
            //        }
        //        loadTable();
    }//GEN-LAST:event_btnDel1ActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        //        try{
            //            if(!fusername.getText().isEmpty() && !fpassword.getText().isEmpty()){
                //                String kolom[] = {"UserName", "UserPass", "UserLevel"};
                //                String value[] = {fusername.getText(), fpassword.getText(), boxuserlevel.getSelectedItem().toString()};
                //                con.queryUpdate("tb_pengguna", kolom, value, "NoAnggota='"+String.valueOf(tblpengguna.getValueAt(tblpengguna.getSelectedRow(), 0))+"'");
                //                lblPesan.setText("Succes, Data Berhasil Diperbaharui");
                //                lblPesan.setForeground(Color.green);
                //            }else{
                //                lblPesan.setText("Error, masih ada data yang belum diisi!");
                //                lblPesan.setForeground(Color.green);
                //            }
            //        }catch(Exception e){
            //            System.out.println(e);
            //        }
        //        loadTable();
        //        clear();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        err_msg.setVisible(true);
        //  createPengguna();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        // loadTable();
        // clear();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        //        if(txtSearch.getText().isEmpty()){
            //            JOptionPane.showMessageDialog(this, "Isikan data Pencarian!!");
            //        }else{
            //            try{
                //                String columnName[] = {"NoAnggota", "UserName", "UserLevel"};
                //                // rs=con.fcSelectCommand(columnName, "tb_pengguna", "NoAnggota LIKE '%"+txtSearch.getText()+"%' OR UserName LIKE '%"+txtSearch.getText()+"%' OR UserLevel LIKE '%"+txtSearch.getText()+"%'");
                //                //  tblpengguna.setModel(new ResultSetTableModel(rs));
                //            }catch(Exception ex){
                //                JOptionPane.showMessageDialog(this, "Pencarian tidak Ditemukan!!");
                //            }
            //        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        btnSearchActionPerformed(evt);
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btnAdd;
    private usu.widget.ButtonGlass btnDel1;
    private usu.widget.ButtonGlass btnEdit;
    private usu.widget.ButtonGlass btnRefresh;
    private usu.widget.ButtonGlass btnSearch;
    private usu.widget.glass.PanelGlass err_msg;
    private javax.swing.JTextField falamat1;
    private javax.swing.JTextField falamat4;
    private javax.swing.JTextField falamat5;
    private javax.swing.JTextField falamat6;
    private javax.swing.JScrollPane jScrollPane1;
    private usu.widget.Label label1;
    private usu.widget.Label label10;
    private usu.widget.Label label11;
    private usu.widget.Label label7;
    private usu.widget.Label label9;
    private usu.widget.Label lblPesan;
    private usu.widget.glass.PanelGlass panelGlass10;
    private usu.widget.glass.PanelGlass panelGlass11;
    private usu.widget.glass.PanelGlass panelGlass12;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    private usu.widget.glass.PanelGlass panelGlass7;
    private javax.swing.JTable tblanggota;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
