/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.transaksi;

import com.query.PemasukanQuery;
import com.query.PembelianQuery;
import com.query.PengeluaranQuery;
import com.service.PembelianService;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARCH
 */
public class Pembelian extends javax.swing.JFrame {
GridBagLayout layout = new GridBagLayout();
java.util.Date tglSekarang = new java.util.Date();

PembelianQuery pembQue;
PengeluaranQuery pengQue;
PemasukanQuery pemQue;
PembelianService pemSvc;

    String TtlByr,idV,Btn,setIdUser;
    private SimpleDateFormat smpdt = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
    private String tanggal = smpdt.format(tglSekarang);
    
    DefaultTableModel model;

    /**
     * Creates new form NewJFrame
     */
    public Pembelian() {
        initComponents();

        tglVw.setText(tanggal);
        tglVw.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        
        //QUery pembelian
        model = new DefaultTableModel();
        pembQue = new PembelianQuery() ;
        pengQue = new PengeluaranQuery() ;
        pemQue = new PemasukanQuery() ;
        pemSvc = new PembelianService();
        
        //menampilkan data
          model.addColumn("ID");
         model.addColumn("Tanggal");
         model.addColumn("Nama Petugas");
         model.addColumn("Nama Barang");
         model.addColumn("Keterangan");
         model.addColumn("Jumlah Barang");
         model.addColumn("Harga Satuan");
         model.addColumn("Harga Total");
        tabelPemb.setModel(model);
        loadTabel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        jLabel3 = new javax.swing.JLabel();
        panelGlass30 = new usu.widget.glass.PanelGlass();
        isiTtlPeng = new javax.swing.JFormattedTextField();
        panelGlass28 = new usu.widget.glass.PanelGlass();
        panelGlass29 = new usu.widget.glass.PanelGlass();
        isiTtlPem = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        errmsg = new usu.widget.glass.PanelGlass();
        lblPesan = new usu.widget.Label();
        panelGlass15 = new usu.widget.glass.PanelGlass();
        panelGlass18 = new usu.widget.glass.PanelGlass();
        jLabel11 = new javax.swing.JLabel();
        panelGlass34 = new usu.widget.glass.PanelGlass();
        isiJmlBr = new javax.swing.JFormattedTextField();
        panelGlass11 = new usu.widget.glass.PanelGlass();
        jLabel6 = new javax.swing.JLabel();
        panelGlass35 = new usu.widget.glass.PanelGlass();
        isiHargaBr1 = new javax.swing.JFormattedTextField();
        panelGlass23 = new usu.widget.glass.PanelGlass();
        jLabel16 = new javax.swing.JLabel();
        panelGlass32 = new usu.widget.glass.PanelGlass();
        isiTtlBr = new javax.swing.JFormattedTextField();
        panelGlass24 = new usu.widget.glass.PanelGlass();
        jLabel18 = new javax.swing.JLabel();
        panelGlass38 = new usu.widget.glass.PanelGlass();
        isiNamaBr = new javax.swing.JTextField();
        panelGlass25 = new usu.widget.glass.PanelGlass();
        panelGlass26 = new usu.widget.glass.PanelGlass();
        ketPemb = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        btnDel = new usu.widget.ButtonGlass();
        btnEdit = new usu.widget.ButtonGlass();
        btnAdd = new usu.widget.ButtonGlass();
        btnRefresh = new usu.widget.ButtonGlass();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPemb = new javax.swing.JTable();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        btnSearch = new usu.widget.ButtonGlass();
        txtSearch = new javax.swing.JTextField();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        label1 = new usu.widget.Label();
        tglVw = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(1366, 590));

        panelGlass5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass5.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass5.setRound(false);

        panelGlass7.setAlpha(1.0F);
        panelGlass7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass7.setRound(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("TOTAL PENGELUARAN");

        panelGlass30.setAlpha(1.0F);
        panelGlass30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass30.setRound(false);

        isiTtlPeng.setBorder(null);
        isiTtlPeng.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiTtlPeng.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiTtlPeng.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass30Layout = new javax.swing.GroupLayout(panelGlass30);
        panelGlass30.setLayout(panelGlass30Layout);
        panelGlass30Layout.setHorizontalGroup(
            panelGlass30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTtlPeng, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass30Layout.setVerticalGroup(
            panelGlass30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTtlPeng, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass7Layout = new javax.swing.GroupLayout(panelGlass7);
        panelGlass7.setLayout(panelGlass7Layout);
        panelGlass7Layout.setHorizontalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panelGlass30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass7Layout.setVerticalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createSequentialGroup()
                .addGroup(panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelGlass28.setAlpha(1.0F);
        panelGlass28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass28.setRound(false);

        panelGlass29.setAlpha(1.0F);
        panelGlass29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass29.setRound(false);

        isiTtlPem.setBorder(null);
        isiTtlPem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiTtlPem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiTtlPem.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass29Layout = new javax.swing.GroupLayout(panelGlass29);
        panelGlass29.setLayout(panelGlass29Layout);
        panelGlass29Layout.setHorizontalGroup(
            panelGlass29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTtlPem, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass29Layout.setVerticalGroup(
            panelGlass29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTtlPem, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Total Pemasukan");

        javax.swing.GroupLayout panelGlass28Layout = new javax.swing.GroupLayout(panelGlass28);
        panelGlass28.setLayout(panelGlass28Layout);
        panelGlass28Layout.setHorizontalGroup(
            panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass28Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass28Layout.setVerticalGroup(
            panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass28Layout.createSequentialGroup()
                .addGroup(panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGlass5Layout = new javax.swing.GroupLayout(panelGlass5);
        panelGlass5.setLayout(panelGlass5Layout);
        panelGlass5Layout.setHorizontalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGlass5Layout.setVerticalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        errmsg.setRound(false);

        lblPesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesan.setFont(new java.awt.Font("Meiryo UI", 0, 10)); // NOI18N

        javax.swing.GroupLayout errmsgLayout = new javax.swing.GroupLayout(errmsg);
        errmsg.setLayout(errmsgLayout);
        errmsgLayout.setHorizontalGroup(
            errmsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errmsgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        errmsgLayout.setVerticalGroup(
            errmsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        panelGlass15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass15.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass15.setRound(false);

        panelGlass18.setAlpha(1.0F);
        panelGlass18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass18.setRound(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Jumlah Barang");

        panelGlass34.setAlpha(1.0F);
        panelGlass34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass34.setRound(false);

        isiJmlBr.setBorder(null);
        isiJmlBr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiJmlBr.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        isiJmlBr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiJmlBrKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGlass34Layout = new javax.swing.GroupLayout(panelGlass34);
        panelGlass34.setLayout(panelGlass34Layout);
        panelGlass34Layout.setHorizontalGroup(
            panelGlass34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiJmlBr, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass34Layout.setVerticalGroup(
            panelGlass34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiJmlBr, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass18Layout = new javax.swing.GroupLayout(panelGlass18);
        panelGlass18.setLayout(panelGlass18Layout);
        panelGlass18Layout.setHorizontalGroup(
            panelGlass18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass18Layout.setVerticalGroup(
            panelGlass18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass18Layout.createSequentialGroup()
                .addComponent(panelGlass34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass11.setAlpha(1.0F);
        panelGlass11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass11.setRound(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Harga Barang");

        panelGlass35.setAlpha(1.0F);
        panelGlass35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass35.setRound(false);

        isiHargaBr1.setBorder(null);
        isiHargaBr1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiHargaBr1.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        isiHargaBr1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiHargaBr1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGlass35Layout = new javax.swing.GroupLayout(panelGlass35);
        panelGlass35.setLayout(panelGlass35Layout);
        panelGlass35Layout.setHorizontalGroup(
            panelGlass35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiHargaBr1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass35Layout.setVerticalGroup(
            panelGlass35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiHargaBr1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass11Layout = new javax.swing.GroupLayout(panelGlass11);
        panelGlass11.setLayout(panelGlass11Layout);
        panelGlass11Layout.setHorizontalGroup(
            panelGlass11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(panelGlass35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass11Layout.setVerticalGroup(
            panelGlass11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass11Layout.createSequentialGroup()
                .addComponent(panelGlass35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass23.setAlpha(1.0F);
        panelGlass23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass23.setRound(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Total");

        panelGlass32.setAlpha(1.0F);
        panelGlass32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass32.setRound(false);

        isiTtlBr.setBorder(null);
        isiTtlBr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiTtlBr.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        isiTtlBr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiTtlBrKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGlass32Layout = new javax.swing.GroupLayout(panelGlass32);
        panelGlass32.setLayout(panelGlass32Layout);
        panelGlass32Layout.setHorizontalGroup(
            panelGlass32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTtlBr, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass32Layout.setVerticalGroup(
            panelGlass32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTtlBr, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass23Layout = new javax.swing.GroupLayout(panelGlass23);
        panelGlass23.setLayout(panelGlass23Layout);
        panelGlass23Layout.setHorizontalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelGlass32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass23Layout.setVerticalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlass32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass24.setAlpha(1.0F);
        panelGlass24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass24.setRound(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Nama Barang");

        panelGlass38.setAlpha(1.0F);
        panelGlass38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass38.setRound(false);

        isiNamaBr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        isiNamaBr.setBorder(null);
        isiNamaBr.setOpaque(false);

        javax.swing.GroupLayout panelGlass38Layout = new javax.swing.GroupLayout(panelGlass38);
        panelGlass38.setLayout(panelGlass38Layout);
        panelGlass38Layout.setHorizontalGroup(
            panelGlass38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiNamaBr, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass38Layout.setVerticalGroup(
            panelGlass38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiNamaBr, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelGlass24Layout = new javax.swing.GroupLayout(panelGlass24);
        panelGlass24.setLayout(panelGlass24Layout);
        panelGlass24Layout.setHorizontalGroup(
            panelGlass24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(panelGlass38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass24Layout.setVerticalGroup(
            panelGlass24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGlass38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass25.setAlpha(1.0F);
        panelGlass25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass25.setRound(false);

        panelGlass26.setAlpha(1.0F);
        panelGlass26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass26.setRound(false);

        ketPemb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ketPemb.setBorder(null);

        javax.swing.GroupLayout panelGlass26Layout = new javax.swing.GroupLayout(panelGlass26);
        panelGlass26.setLayout(panelGlass26Layout);
        panelGlass26Layout.setHorizontalGroup(
            panelGlass26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ketPemb, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass26Layout.setVerticalGroup(
            panelGlass26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ketPemb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Keterangan");

        javax.swing.GroupLayout panelGlass25Layout = new javax.swing.GroupLayout(panelGlass25);
        panelGlass25.setLayout(panelGlass25Layout);
        panelGlass25Layout.setHorizontalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(panelGlass26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass25Layout.setVerticalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass25Layout.createSequentialGroup()
                .addGroup(panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGlass15Layout = new javax.swing.GroupLayout(panelGlass15);
        panelGlass15.setLayout(panelGlass15Layout);
        panelGlass15Layout.setHorizontalGroup(
            panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelGlass25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelGlass15Layout.setVerticalGroup(
            panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        panelGlass3.setAlpha(0.0F);
        panelGlass3.setRound(false);

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_delete.png"))); // NOI18N
        btnDel.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnDel.setPreferredSize(new java.awt.Dimension(117, 41));
        btnDel.setRoundRect(true);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_edit.png"))); // NOI18N
        btnEdit.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(117, 41));
        btnEdit.setRoundRect(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_new.png"))); // NOI18N
        btnAdd.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnAdd.setRoundRect(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_refresh.png"))); // NOI18N
        btnRefresh.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(117, 41));
        btnRefresh.setRoundRect(true);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tabelPemb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Saldo", "Nominal Saldo", "Keterangan"
            }
        ));
        tabelPemb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPembMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPemb);

        panelGlass2.setAlpha(1.0F);
        panelGlass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass2.setRound(false);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btn_search.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass2Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        panelGlass4.setAlpha(0.0F);
        panelGlass4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        panelGlass4.setPreferredSize(new java.awt.Dimension(264, 54));
        panelGlass4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(153, 153, 153));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Pembelian");
        label1.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        label1.setOpaque(true);
        panelGlass4.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 280, 30));

        tglVw.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tglVw.setForeground(new java.awt.Color(255, 255, 255));
        tglVw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tglVw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panelGlass15, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelGlass5, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(97, 97, 97)
                            .addComponent(errmsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8))
                        .addComponent(panelGlass3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errmsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass15, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1, 18));

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Exit");
        jMenu1.setOpaque(true);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("EXIT");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1173, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1156, 646));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void isiJmlBrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiJmlBrKeyTyped
        // TODO add your handling code here:
        matvv();
    }//GEN-LAST:event_isiJmlBrKeyTyped

    private void isiHargaBr1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiHargaBr1KeyTyped
        // TODO add your handling code here:
        matvv();
    }//GEN-LAST:event_isiHargaBr1KeyTyped

    private void isiTtlBrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiTtlBrKeyTyped
        // TODO add your handling code here:
        matvv();
    }//GEN-LAST:event_isiTtlBrKeyTyped

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        delAction();
        loadTabel();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here;
        editAction();
        loadTabel();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addAction();
        loadTabel();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        //clear();
        loadTabel();
        clear();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tabelPembMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPembMouseClicked
        // TODO add your handling code here:
        tabelMouseAction();
    }//GEN-LAST:event_tabelPembMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //        // TODO add your handling code here:
        ssearchAction();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
        ssearchAction();
    }//GEN-LAST:event_txtSearchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btnAdd;
    private usu.widget.ButtonGlass btnDel;
    private usu.widget.ButtonGlass btnEdit;
    private usu.widget.ButtonGlass btnRefresh;
    private usu.widget.ButtonGlass btnSearch;
    private usu.widget.glass.PanelGlass errmsg;
    private javax.swing.JFormattedTextField isiHargaBr1;
    private javax.swing.JFormattedTextField isiJmlBr;
    private javax.swing.JTextField isiNamaBr;
    private javax.swing.JFormattedTextField isiTtlBr;
    private javax.swing.JFormattedTextField isiTtlPem;
    private javax.swing.JFormattedTextField isiTtlPeng;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ketPemb;
    private usu.widget.Label label1;
    private usu.widget.Label lblPesan;
    private usu.widget.glass.PanelGlass panelGlass11;
    private usu.widget.glass.PanelGlass panelGlass15;
    private usu.widget.glass.PanelGlass panelGlass18;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass23;
    private usu.widget.glass.PanelGlass panelGlass24;
    private usu.widget.glass.PanelGlass panelGlass25;
    private usu.widget.glass.PanelGlass panelGlass26;
    private usu.widget.glass.PanelGlass panelGlass28;
    private usu.widget.glass.PanelGlass panelGlass29;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass30;
    private usu.widget.glass.PanelGlass panelGlass32;
    private usu.widget.glass.PanelGlass panelGlass34;
    private usu.widget.glass.PanelGlass panelGlass35;
    private usu.widget.glass.PanelGlass panelGlass38;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass7;
    private javax.swing.JTable tabelPemb;
    private javax.swing.JLabel tglVw;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
 
     public void clear(){
        //err_msg.setText("");
        isiNamaBr.setText("");
        isiJmlBr.setText("");
        isiHargaBr1.setText("");
        isiTtlBr.setText("");
        Btn=null;;
        TtlByr=null;
        idV=null;
        isiTtlBr.setText("");
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDel.setEnabled(true);

    }
    
    private void loadTabel(){
        List<String[]> result = pembQue.viewTotalPembelian(tglVw);
        String tglPembelian;
        tglPembelian = tglVw.getText().trim();
        //////////////////////////////////////////////
        pengQue.viewTotalPengeluaran(tglVw,isiTtlPeng);
        pemQue.viewTotalPemasukan(tglVw, isiTtlPem);
        /////////////////////////////////////////////
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        tabelPemb.setModel(model);
        for(int i = 0; i < result.size();i++){
            model.addRow(result.get(i));
        }
        tabelPemb.repaint();
        model.fireTableDataChanged();
        focus();
        clear();
    }
    
     private void matvv(){
        if(!isiJmlBr.getText().isEmpty()){
            if(!isiHargaBr1.getText().isEmpty()){
                BigDecimal Bay = new BigDecimal(isiHargaBr1.getText());
                String x = String.valueOf(isiJmlBr.getValue());
                BigDecimal Sal = new BigDecimal(x);
                BigDecimal Juml = Bay.multiply(Sal);
                isiTtlBr.setValue(Juml);
            } 
        }else{
            isiHargaBr1.setText("");
            isiTtlBr.setText("");
        }
    }
    
    private void addAction(){
        
        if(isiTtlBr.getText().isEmpty()){
            if(isiHargaBr1.getText().isEmpty()){
                if(isiJmlBr.getText().isEmpty()){
                    if(isiNamaBr.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this, "Isi Nama Barang!");
                    }else{
                        JOptionPane.showMessageDialog(this, "Isi Jumlah Barang!");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Isi Harga Barang!");
                }
            } else{
                String isiPem = String.valueOf(isiTtlPem.getValue());
                BigDecimal isiPm = new BigDecimal(isiPem);
                if(isiPem.equals(BigDecimal.ZERO)){
                    JOptionPane.showMessageDialog(this, "Pemasukan Kosong! Tidak bisa melakukan pembelian");
                }
            }
        }else{
            String isiPem = String.valueOf(isiTtlPem.getValue());
            BigDecimal isiPm = new BigDecimal(isiPem);
            String ttlBr = String.valueOf(isiTtlBr.getValue());
            BigDecimal ttl = new BigDecimal(ttlBr);
            if(isiPm.compareTo(BigDecimal.ZERO) <0||isiPm.compareTo(ttl)<0){
                JOptionPane.showMessageDialog(this, "Jumlah pemasukan tidak memenuhi! Tidak bisa melakukan pembelian");
            }else{
                    try{
                    //prodQue.insertInto(tglVw,isiSaldo,isiKeterangan);
                    MatEdit();
                    //System.out.println(""+isiTotalSaldo.getText());          
                    lblPesan.setText(" Berhasil ditambahkan! ");
                    lblPesan.setForeground(Color.green);
                    }
                    catch(Exception e){
                    lblPesan.setText(" Gagal ditambahkan! ");
                    lblPesan.setForeground(Color.red);
                    }  
            }
        }
    }
    
    private void editAction(){
         
                    try{
                    //prodQue.insertInto(tglVw,isiSaldo,isiKeterangan);
                    MatEdit();
                    //System.out.println(""+isiTotalSaldo.getText());          
                    lblPesan.setText(" Berhasil Edit! ");
                    lblPesan.setForeground(Color.green);
                    }
                    catch(Exception e){
                    lblPesan.setText(" Gagal Edit! ");
                    lblPesan.setForeground(Color.red);
                    }
    }
    
    private void delAction(){
                    try{
                    MatEdit();      
                    lblPesan.setText(" Berhasil Delete! ");
                    lblPesan.setForeground(Color.green);
                    }
                    catch(Exception e){
                    lblPesan.setText(" Gagal Delete! ");
                    lblPesan.setForeground(Color.red);
                    }  
    }
    
    private void MatEdit(){

            if(TtlByr==null && !isiNamaBr.getText().isEmpty()){
                String isiPem = String.valueOf(isiTtlPem.getValue());
                BigDecimal isiPm = new BigDecimal(isiPem);
                String ttlBr = String.valueOf(isiTtlBr.getValue());
                BigDecimal ttl = new BigDecimal(ttlBr);
                if(isiPm.compareTo(BigDecimal.ZERO) <0||isiPm.compareTo(ttl)<0){
                    JOptionPane.showMessageDialog(this, "Jumlah pemasukan tidak memenuhi! Tidak bisa melakukan pembelian");
                }else{
                    pemSvc.tambah(isiTtlBr,isiTtlPeng,isiTtlPem);
                    pembQue.insertIntoPembelian(tglVw,setIdUser,isiNamaBr,isiHargaBr1,isiJmlBr,isiTtlBr,ketPemb);//diinputkan
                }
            }else{
                if(!isiTtlBr.getText().equals(TtlByr)){
                    String isiPem = String.valueOf(isiTtlPem.getValue());
                    BigDecimal isiPm = new BigDecimal(isiPem);
                    String ttlBr = String.valueOf(isiTtlBr.getValue());
                    BigDecimal ttl = new BigDecimal(ttlBr);
                    if(isiPm.compareTo(BigDecimal.ZERO) <0||isiPm.compareTo(ttl)<0){
                        JOptionPane.showMessageDialog(this, "Jumlah pemasukan tidak memenuhi! Tidak bisa melakukan pembelian");
                    }else{
                        pemSvc.edit(TtlByr,isiTtlBr,isiTtlPeng,isiTtlPem);
                        pembQue.editPembelian(idV,isiNamaBr,isiHargaBr1,isiJmlBr,isiTtlBr,ketPemb);
                    }
                }else{
                    if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){                   
                        pemSvc.delMat(TtlByr,isiTtlPeng,isiTtlPem);
                        pembQue.delPembelian(idV);
                    }
                }
            }

        pengQue.editPengeluaran(tglVw,isiTtlPeng);//ditambah
        pemQue.editPemasukan(tglVw,isiTtlPem);//ditambah
    }
    
      private void tabelMouseAction() {
       //To change body of generated methods, choose Tools | Templates.
        btnAdd.setEnabled(false);
        int row = tabelPemb.getSelectedRow();
        idV=tabelPemb.getModel().getValueAt(row,0).toString();
        isiNamaBr.setText(tabelPemb.getModel().getValueAt(row,3).toString());
        ketPemb.setText(tabelPemb.getModel().getValueAt(row,4).toString());
        isiJmlBr.setText(tabelPemb.getModel().getValueAt(row,5).toString());
        isiHargaBr1.setText(tabelPemb.getModel().getValueAt(row,6).toString());
        isiTtlBr.setText(tabelPemb.getModel().getValueAt(row,7).toString());
        TtlByr =tabelPemb.getModel().getValueAt(row,7).toString();
    }
      
        private void ssearchAction() {
       //To change body of generated methods, choose Tools | Templates.
            try{
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                tabelPemb.setModel(model);
                List<String[]> result=  pembQue.fcSelectCommand(txtSearch);
                for(int i = 0; i < result.size();i++){
                     model.addRow(result.get(i));
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Pencarian tidak Ditemukan!!");
            }
    }
        
        private void focus(){
        jPanel2.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                //isiTtlBr.requestFocusInWindow();
                isiTtlPeng.requestFocusInWindow();
                isiTtlPem.requestFocusInWindow();
            }
        });
     }
    public void setUser(String USER, String id) {
       //To change body of generated methods, choose Tools | Templates.
        setIdUser=id;
    }
}

