/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.transaksi;

import com.query.PemasukanQuery;
import com.query.PemsSaldoQuery;
import com.query.PembelianQuery;
import com.query.SaldoQuery;
import com.service.SaldoService;
import com.sia.ui.aruskas.InsertSaldo;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARCH
 */
public class saldoInsedintil extends javax.swing.JFrame {
    GridBagLayout layout = new GridBagLayout();

PemsSaldoQuery pemdoQue;
SaldoQuery saldoQue;
PembelianQuery pengeQue;
PemasukanQuery pemQue;
SaldoService saldoServ;

DefaultTableModel model;
java.util.Date tglSekarang = new java.util.Date();
    
    String setIdUser;
    private SimpleDateFormat smpdt = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
    private String tanggal = smpdt.format(tglSekarang);

    public saldoInsedintil() {
        initComponents();
       
        tglVw.setText(tanggal);
        pemdoQue = new PemsSaldoQuery();
        saldoQue = new SaldoQuery();
        pemQue = new PemasukanQuery();
        model = new DefaultTableModel();
        //BynganNom.setText("0");

       //contruct metode matematika
        saldoServ = new SaldoService();
        //contruct tanggal
        tglVw.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
       // c.gridx = 0;
        //c.gridy = 0;
    
        //menampilkan data
        model.addColumn("Id");
        model.addColumn("Tanggal");
        model.addColumn("Nama Petugas");
        model.addColumn("Saldo Tambahan");
        model.addColumn("Status Saldo");
        model.addColumn("Keterangan");
        tabelSaldo.setModel(model);
        loadTabel();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        err_msg1 = new usu.widget.glass.PanelGlass();
        err_msg = new usu.widget.Label();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        btnDel = new usu.widget.ButtonGlass();
        btnEdit = new usu.widget.ButtonGlass();
        btnAdd = new usu.widget.ButtonGlass();
        btnRefresh = new usu.widget.ButtonGlass();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSaldo = new javax.swing.JTable();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        btnSearch = new usu.widget.ButtonGlass();
        txtSearch = new javax.swing.JTextField();
        tglVw = new javax.swing.JLabel();
        panelGlass16 = new usu.widget.glass.PanelGlass();
        panelGlass10 = new usu.widget.glass.PanelGlass();
        isiKeterangan = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        panelGlass22 = new usu.widget.glass.PanelGlass();
        panelGlass25 = new usu.widget.glass.PanelGlass();
        isiSaldo = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        panelGlass23 = new usu.widget.glass.PanelGlass();
        panelGlass26 = new usu.widget.glass.PanelGlass();
        ketSal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        panelGlass9 = new usu.widget.glass.PanelGlass();
        panelGlass24 = new usu.widget.glass.PanelGlass();
        panelGlass28 = new usu.widget.glass.PanelGlass();
        isiTotalSaldo = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        panelGlass29 = new usu.widget.glass.PanelGlass();
        panelGlass30 = new usu.widget.glass.PanelGlass();
        isiTtlPemasukan = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        label1 = new usu.widget.Label();
        idV = new javax.swing.JTextField();
        Bay = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 590));

        err_msg1.setRound(false);

        err_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        err_msg.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout err_msg1Layout = new javax.swing.GroupLayout(err_msg1);
        err_msg1.setLayout(err_msg1Layout);
        err_msg1Layout.setHorizontalGroup(
            err_msg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(err_msg1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(err_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        err_msg1Layout.setVerticalGroup(
            err_msg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(err_msg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        panelGlass3.setAlpha(0.0F);
        panelGlass3.setRound(false);

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_delete.png"))); // NOI18N
        btnDel.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnDel.setPreferredSize(new java.awt.Dimension(117, 41));
        btnDel.setRoundRect(true);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_edit.png"))); // NOI18N
        btnEdit.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(117, 41));
        btnEdit.setRoundRect(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_new.png"))); // NOI18N
        btnAdd.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnAdd.setRoundRect(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_refresh.png"))); // NOI18N
        btnRefresh.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(117, 41));
        btnRefresh.setRoundRect(true);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tabelSaldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Saldo", "Nominal Saldo", "Keterangan"
            }
        ));
        tabelSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSaldoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSaldo);

        panelGlass2.setAlpha(1.0F);
        panelGlass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass2.setRound(false);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btn_search.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass2Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGlass3Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        tglVw.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tglVw.setForeground(new java.awt.Color(255, 255, 255));
        tglVw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tglVw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        panelGlass16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass16.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass16.setRound(false);

        panelGlass10.setAlpha(1.0F);
        panelGlass10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass10.setRound(false);

        isiKeterangan.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        isiKeterangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "saldo tambahan", "saldo usaha tambahan" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Status");

        javax.swing.GroupLayout panelGlass10Layout = new javax.swing.GroupLayout(panelGlass10);
        panelGlass10.setLayout(panelGlass10Layout);
        panelGlass10Layout.setHorizontalGroup(
            panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass10Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isiKeterangan, 0, 218, Short.MAX_VALUE))
        );
        panelGlass10Layout.setVerticalGroup(
            panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isiKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelGlass22.setAlpha(1.0F);
        panelGlass22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass22.setRound(false);

        panelGlass25.setAlpha(1.0F);
        panelGlass25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass25.setRound(false);

        isiSaldo.setBorder(null);
        isiSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiSaldo.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass25Layout = new javax.swing.GroupLayout(panelGlass25);
        panelGlass25.setLayout(panelGlass25Layout);
        panelGlass25Layout.setHorizontalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiSaldo)
                .addContainerGap())
        );
        panelGlass25Layout.setVerticalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nominal");

        javax.swing.GroupLayout panelGlass22Layout = new javax.swing.GroupLayout(panelGlass22);
        panelGlass22.setLayout(panelGlass22Layout);
        panelGlass22Layout.setHorizontalGroup(
            panelGlass22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass22Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass22Layout.setVerticalGroup(
            panelGlass22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass22Layout.createSequentialGroup()
                .addGroup(panelGlass22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass23.setAlpha(1.0F);
        panelGlass23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass23.setRound(false);

        panelGlass26.setAlpha(1.0F);
        panelGlass26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass26.setRound(false);

        ketSal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ketSal.setBorder(null);

        javax.swing.GroupLayout panelGlass26Layout = new javax.swing.GroupLayout(panelGlass26);
        panelGlass26.setLayout(panelGlass26Layout);
        panelGlass26Layout.setHorizontalGroup(
            panelGlass26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ketSal)
                .addContainerGap())
        );
        panelGlass26Layout.setVerticalGroup(
            panelGlass26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ketSal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Keterangan");

        javax.swing.GroupLayout panelGlass23Layout = new javax.swing.GroupLayout(panelGlass23);
        panelGlass23.setLayout(panelGlass23Layout);
        panelGlass23Layout.setHorizontalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass23Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass23Layout.setVerticalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass23Layout.createSequentialGroup()
                .addGroup(panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGlass16Layout = new javax.swing.GroupLayout(panelGlass16);
        panelGlass16.setLayout(panelGlass16Layout);
        panelGlass16Layout.setHorizontalGroup(
            panelGlass16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGlass16Layout.setVerticalGroup(
            panelGlass16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        panelGlass9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass9.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass9.setRound(false);

        panelGlass24.setAlpha(1.0F);
        panelGlass24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass24.setRound(false);

        panelGlass28.setAlpha(1.0F);
        panelGlass28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass28.setRound(false);

        isiTotalSaldo.setBorder(null);
        isiTotalSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiTotalSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiTotalSaldo.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass28Layout = new javax.swing.GroupLayout(panelGlass28);
        panelGlass28.setLayout(panelGlass28Layout);
        panelGlass28Layout.setHorizontalGroup(
            panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTotalSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass28Layout.setVerticalGroup(
            panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTotalSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Total Saldo");

        javax.swing.GroupLayout panelGlass24Layout = new javax.swing.GroupLayout(panelGlass24);
        panelGlass24.setLayout(panelGlass24Layout);
        panelGlass24Layout.setHorizontalGroup(
            panelGlass24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass24Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(panelGlass28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass24Layout.setVerticalGroup(
            panelGlass24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass24Layout.createSequentialGroup()
                .addGroup(panelGlass24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass29.setAlpha(1.0F);
        panelGlass29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass29.setRound(false);

        panelGlass30.setAlpha(1.0F);
        panelGlass30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass30.setRound(false);

        isiTtlPemasukan.setBorder(null);
        isiTtlPemasukan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiTtlPemasukan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiTtlPemasukan.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass30Layout = new javax.swing.GroupLayout(panelGlass30);
        panelGlass30.setLayout(panelGlass30Layout);
        panelGlass30Layout.setHorizontalGroup(
            panelGlass30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTtlPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass30Layout.setVerticalGroup(
            panelGlass30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTtlPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Total Pemasukan");

        javax.swing.GroupLayout panelGlass29Layout = new javax.swing.GroupLayout(panelGlass29);
        panelGlass29.setLayout(panelGlass29Layout);
        panelGlass29Layout.setHorizontalGroup(
            panelGlass29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass29Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass29Layout.setVerticalGroup(
            panelGlass29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass29Layout.createSequentialGroup()
                .addGroup(panelGlass29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGlass9Layout = new javax.swing.GroupLayout(panelGlass9);
        panelGlass9.setLayout(panelGlass9Layout);
        panelGlass9Layout.setHorizontalGroup(
            panelGlass9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGlass9Layout.setVerticalGroup(
            panelGlass9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        panelGlass4.setAlpha(0.0F);
        panelGlass4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        panelGlass4.setPreferredSize(new java.awt.Dimension(264, 54));
        panelGlass4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setBackground(new java.awt.Color(153, 153, 153));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Saldo Tambahan");
        label1.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        label1.setOpaque(true);
        panelGlass4.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 280, 30));

        idV.setBackground(new java.awt.Color(0, 153, 204));
        idV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idV.setForeground(new java.awt.Color(51, 51, 51));
        idV.setBorder(null);

        Bay.setBackground(new java.awt.Color(0, 153, 204));
        Bay.setBorder(null);
        Bay.setForeground(new java.awt.Color(51, 51, 51));
        Bay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        Bay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Bay.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(err_msg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(panelGlass16, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelGlass9, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bay, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(err_msg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelGlass16, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelGlass9, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1, 20));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Exit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1019, 666));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        delAction();

    }//GEN-LAST:event_btnDelActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        editAction();

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addAction();

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadTabel();
        clear();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tabelSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSaldoMouseClicked
        // TODO add your handling code here:
        tabelMouseAction();
    }//GEN-LAST:event_tabelSaldoMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //        // TODO add your handling code here:
        ssearchAction();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        btnSearchActionPerformed(evt);
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(saldoInsedintil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(saldoInsedintil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(saldoInsedintil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(saldoInsedintil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new saldoInsedintil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Bay;
    private usu.widget.ButtonGlass btnAdd;
    private usu.widget.ButtonGlass btnDel;
    private usu.widget.ButtonGlass btnEdit;
    private usu.widget.ButtonGlass btnRefresh;
    private usu.widget.ButtonGlass btnSearch;
    private usu.widget.Label err_msg;
    private usu.widget.glass.PanelGlass err_msg1;
    private javax.swing.JTextField idV;
    private javax.swing.JComboBox isiKeterangan;
    private javax.swing.JFormattedTextField isiSaldo;
    private javax.swing.JFormattedTextField isiTotalSaldo;
    private javax.swing.JFormattedTextField isiTtlPemasukan;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ketSal;
    private usu.widget.Label label1;
    private usu.widget.glass.PanelGlass panelGlass10;
    private usu.widget.glass.PanelGlass panelGlass16;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass22;
    private usu.widget.glass.PanelGlass panelGlass23;
    private usu.widget.glass.PanelGlass panelGlass24;
    private usu.widget.glass.PanelGlass panelGlass25;
    private usu.widget.glass.PanelGlass panelGlass26;
    private usu.widget.glass.PanelGlass panelGlass28;
    private usu.widget.glass.PanelGlass panelGlass29;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass30;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass9;
    private javax.swing.JTable tabelSaldo;
    private javax.swing.JLabel tglVw;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
 
   
    
    
    public void clear(){
        //err_msg.setText("");
        isiSaldo.setText("");
        Bay.setText("");
        idV.setText("");
        isiKeterangan.setEnabled(true);
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDel.setEnabled(true);
    } 
    
    private void loadTabel(){
        isiTotalSaldo.setFocusable(true);
        List<String[]> result = pemdoQue.viewSaldoTambahan(tglVw);
        String TGL_SALDO;
        TGL_SALDO = tglVw.getText().trim();
        saldoQue.viewTotalSaldo(tglVw,isiTotalSaldo);
        pemQue.viewTotalPemasukan(tglVw,isiTtlPemasukan);/// TANDA TANYA KETIKA PROYEKSI ARUSKAS <OK ATAU BELUM>
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        tabelSaldo.setModel(model);
        for(int i = 0; i < result.size();i++){
            model.addRow(result.get(i));
        }
        tabelSaldo.repaint();
        model.fireTableDataChanged();
        focus();
        clear();
    }
    
    private void addAction() {
        /**sebelum melakukan add
         * kondisikan memilih input dan keterangan
        */ 
        if(isiSaldo.getText().isEmpty()){
            if(isiTotalSaldo.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Isikan Nominal Saldo!! Saldo Hari ini Kosong");
            } else{
                JOptionPane.showMessageDialog(this, "Isikan Nominal Saldo");
            }
        } else{
            String isiSldo = String.valueOf(isiSaldo.getValue());
            BigDecimal isiSld = new BigDecimal(isiSldo);
            if(isiSld.compareTo(BigDecimal.ZERO)>0){
                String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
                    BigDecimal nomTtlSldo = new BigDecimal(isiTtlSaldo);
                if(!isiTotalSaldo.getText().isEmpty()){
                    if(nomTtlSldo.equals(BigDecimal.ZERO)){
                        if(JOptionPane.showConfirmDialog(this, "Masukkan Saldo dulu!!", "Peringatan", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION){
                           MatEdit();
                        }
                    }else{
                        if(isiKeterangan.getSelectedItem()!= "saldo tambahan"&&isiKeterangan.getSelectedItem()!= "saldo usaha tambahan"){//harus sama persis
                            JOptionPane.showMessageDialog(this, " Ganti Status Saldo 'Saldo Tambahan' atau 'Saldo Usaha Tambahan'!! ");
                        }else{
                            try{
                                //prodQue.insertInto(tglVw,isiSaldo,isiKeterangan);
                                 MatEdit();
                                //System.out.println(""+isiTotalSaldo.getText());
                                err_msg.setText(" Berhasil ditambahkan! ");
                                err_msg.setForeground(Color.green);
                            }
                            catch(Exception e){
                                err_msg.setText(" Gagal ditambahkan! ");
                                err_msg.setForeground(Color.red);
                            }  
                        }
                    }
                }else {///fix gak usah pakai hitungan tambah untuk SALDO TAMBAHAN
                    if(isiKeterangan.getSelectedItem()== "saldo tambahan"||isiKeterangan.getSelectedItem()== "saldo usaha tambahan"){
                        JOptionPane.showMessageDialog(this, "Ganti Status Saldo 'Saldo Usaha'!!");
                    } else if (isiKeterangan.getSelectedItem()== "saldo usaha"){
                        try{
                            insertMat();
                            err_msg.setText(" Berhasil ditambahkan! ");
                            err_msg.setForeground(Color.green);
                        }
                        catch(Exception e){
                        err_msg.setText(" Gagal ditambahkan! ");
                        err_msg.setForeground(Color.red);
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, " jangan Gunakan 0 ");
                isiSaldo.setText("");
            }
            loadTabel();
        }
        
    }    
    
      private void editAction() {
     //To change body of generated methods, choose Tools | Templates.
        try {
            MatEdit();
            err_msg.setText("Berhasil diedit!");
            err_msg.setForeground(Color.green);
            //JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        catch(Exception ex){
        // Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
            err_msg.setText("Gagal diedit!");
            err_msg.setForeground(Color.red);
            //JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
        loadTabel();
    }
      
      private void delAction(){
          try{
             MatEdit();
              err_msg.setText("Berhasil diHapus!");
              err_msg.setForeground(Color.green); 
          }catch (Exception ex){
              err_msg.setText("Gagal diHapus!");
              err_msg.setForeground(Color.red);
          }
          loadTabel();
      }
    
    public void MatEdit(){
         if(Bay.getText().isEmpty()){
            String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
            BigDecimal ttlSldo = new BigDecimal(isiTtlSaldo);
            if(ttlSldo.compareTo(BigDecimal.ONE) == 0){
                isiTotalSaldo.setText("0");
                saldoServ.addMat(isiSaldo, isiTotalSaldo,isiTtlPemasukan);
            }else{
                saldoServ.addMat(isiSaldo,isiTotalSaldo,isiTtlPemasukan);
            }
            pemdoQue.insertInto(tglVw,setIdUser,isiSaldo,isiKeterangan,ketSal);
        }else{
            String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
            BigDecimal ttlSldo = new BigDecimal(isiTtlSaldo);
            String isiTtlpem = String.valueOf(isiTtlPemasukan.getValue());
            BigDecimal pem = new BigDecimal(isiTtlpem);
            if(ttlSldo.compareTo(BigDecimal.ZERO) > 0 && pem.compareTo(BigDecimal.ZERO)>0){
                if(!isiSaldo.getText().equals(Bay.getText())){
                    saldoServ.editMat(isiSaldo,Bay,isiTotalSaldo,isiTtlPemasukan);
                }else{
                 if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                        saldoServ.delMat(Bay,isiTotalSaldo,isiTtlPemasukan);
                        pemdoQue.delete(idV);
                    }
             }
              pemdoQue.edit(idV,isiSaldo);
            } else {
                JOptionPane.showMessageDialog(this, "ditambah saldo dulu");
            }
            
         }
        saldoQue.editTotalSaldoUsaha(tglVw,isiTotalSaldo);
        pemQue.editPemasukan(tglVw, isiTtlPemasukan);
    }
    
    private void tabelMouseAction() {
       //To change body of generated methods, choose Tools | Templates.
        btnAdd.setEnabled(false);
        isiKeterangan.setEnabled(false);
        int row = tabelSaldo.getSelectedRow();
        idV.setText(tabelSaldo.getModel().getValueAt(row,0).toString());
        isiSaldo.setText(tabelSaldo.getModel().getValueAt(row,3).toString());
        Bay.setText(tabelSaldo.getModel().getValueAt(row,3).toString());
        ketSal.setText(tabelSaldo.getModel().getValueAt(row,5).toString());
    }
    
    private void insertMat(){
        String NOM_SALDO = String.valueOf(isiSaldo.getValue());
        if(isiTtlPemasukan.getText().isEmpty()){
            pemQue.editPemasukan(tglVw,isiSaldo);
        }else{
             String TTL_PEM=String.valueOf(isiTtlPemasukan.getValue());
            
             BigDecimal TTLpem = new BigDecimal(TTL_PEM);
             BigDecimal nomSaldo = new BigDecimal(NOM_SALDO);
            
             BigDecimal zzz = nomSaldo.add(TTLpem);
                       
             isiTtlPemasukan.setValue(zzz);  
        }
          //  pemQue.editPemasukan(tglVw,isiTtlPemasukan);
        saldoQue.insertIntoSS(isiSaldo,tglVw);
        pemdoQue.insertInto(tglVw,setIdUser,isiSaldo,isiKeterangan,ketSal);
    }
    
     private void ssearchAction() {
       //To change body of generated methods, choose Tools | Templates.
            try{
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                tabelSaldo.setModel(model);
                List<String[]> result=  pemdoQue.fcSelectCommand(txtSearch);
                String search;
                search = txtSearch.getText().trim();
                for(int i = 0; i < result.size();i++){
                     model.addRow(result.get(i));
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Pencarian tidak Ditemukan!!");
            }
    }
     
     private void focus(){
        jPanel1.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                isiTotalSaldo.requestFocusInWindow();
                isiTtlPemasukan.requestFocusInWindow();

                
            }
        });
     }
     public void setUser(String USER, String id) {
       //To change body of generated methods, choose Tools | Templates.
        setIdUser=id;
    }
}
