/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.mainInterface;

import com.jamtgl.Jam;
import com.jamtgl.Tgl;
import com.query.PemsSaldoQuery;
import com.sia.ui.pengaman.fLogin;
import com.sia.ui.aruskas.Aruskas;
import com.sia.ui.laporan.Laporan;
import com.sia.ui.master.Produk;
import com.sia.ui.master.Pelanggan;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;
     


/**
 *
 * @author ARCH
 */
public class Akuntansi extends javax.swing.JFrame {
    GridBagLayout layout = new GridBagLayout();
    PemsSaldoQuery prod = new PemsSaldoQuery();
    Pelanggan p1;
    Laporan lp;
    Produk pr;
    Aruskas pn;
    Jam jt;
    Tgl tgl;
    
    String setIdUser;
    //Panel2 p2;
    /**
     * Creates new form NewJFrame
     */
    public Akuntansi() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(false);
        DynamicPanel.setLayout(layout);
        jamVw.setLayout(layout);
        tglVw.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
       
        //jam
        jt = new Jam();
        jamVw.add(jt);
        jt.setVisible(true);
        jamVw.repaint();
        jamVw.revalidate();
        
        //tgl
        tgl = new Tgl();
        tglVw.add(tgl);
        tgl.setVisible(true);
        tglVw.repaint();
        tglVw.revalidate();
        
        //c.gridx = 0;
        //c.gridy = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlass1 = new usu.widget.glass.PanelGlass();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        btnLaporan = new usu.widget.ButtonGlass();
        btnAruskas = new usu.widget.ButtonGlass();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        btnLogout = new usu.widget.ButtonGlass();
        jButton1 = new javax.swing.JButton();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        jamVw = new javax.swing.JLabel();
        tglVw = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1364, 745));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass1.setAlpha(1.0F);
        panelGlass1.setBackground(new java.awt.Color(255, 255, 255));
        panelGlass1.setMinimumSize(new java.awt.Dimension(1366, 745));
        panelGlass1.setPreferredSize(new java.awt.Dimension(1366, 745));
        panelGlass1.setRound(false);
        panelGlass1.setWarna(new java.awt.Color(0, 0, 0));
        panelGlass1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass2.setAlpha(0.0F);
        panelGlass2.setPreferredSize(new java.awt.Dimension(733, 493));
        panelGlass2.setRound(false);

        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnLaporan.png"))); // NOI18N
        btnLaporan.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnAruskas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        btnAruskas.setForeground(new java.awt.Color(255, 255, 255));
        btnAruskas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnAruskas1.png"))); // NOI18N
        btnAruskas.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnAruskas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAruskasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnAruskas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAruskas, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelGlass1.add(panelGlass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 70));

        panelGlass4.setAlpha(0.0F);
        panelGlass4.setRound(false);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnLogout.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass4Layout = new javax.swing.GroupLayout(panelGlass4);
        panelGlass4.setLayout(panelGlass4Layout);
        panelGlass4Layout.setHorizontalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass4Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        panelGlass4Layout.setVerticalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelGlass1.add(panelGlass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1216, -1, 150, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelGlass1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        panelGlass6.setBackground(new java.awt.Color(51, 51, 51));
        panelGlass6.setOpaque(true);
        panelGlass6.setRound(false);

        jamVw.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jamVw.setForeground(new java.awt.Color(255, 255, 255));
        jamVw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jamVw.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jamVwAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tglVw.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tglVw.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelGlass6Layout = new javax.swing.GroupLayout(panelGlass6);
        panelGlass6.setLayout(panelGlass6Layout);
        panelGlass6Layout.setHorizontalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jamVw, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass6Layout.setVerticalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglVw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGlass6Layout.createSequentialGroup()
                        .addComponent(jamVw, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelGlass1.add(panelGlass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 290, 70));

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelGlass1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelGlass1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        panelGlass7.setBackground(new java.awt.Color(51, 51, 51));
        panelGlass7.setOpaque(true);
        panelGlass7.setRound(false);

        user.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AKUNTANSI");

        javax.swing.GroupLayout panelGlass7Layout = new javax.swing.GroupLayout(panelGlass7);
        panelGlass7.setLayout(panelGlass7Layout);
        panelGlass7Layout.setHorizontalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass7Layout.setVerticalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass1.add(panelGlass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 250, -1));

        getContentPane().add(panelGlass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        DynamicPanel.setBackground(new java.awt.Color(0, 0, 0));
        DynamicPanel.setBorder(new javax.swing.border.MatteBorder(null));
        DynamicPanel.setPreferredSize(new java.awt.Dimension(1366, 650));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1368, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1370, 660));

        setBounds(0, 0, 1382, 783);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAruskasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAruskasActionPerformed
        // TODO add your handling code here:
        
          //remove
        DynamicPanel.removeAll();
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        
        //adding panel
        pn = new Aruskas(setIdUser);
        DynamicPanel.add(pn);
        pn.setVisible(true);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
    }//GEN-LAST:event_btnAruskasActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        
        //remove
        DynamicPanel.removeAll();
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        
        //adding panel
        lp = new Laporan();
        DynamicPanel.add(lp);
        lp.setVisible(true);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        tglVw.setVisible(true);
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        fLogin login = new fLogin();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        new Master().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         this.dispose();
        new TranIfram().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Manager().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jamVwAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jamVwAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jamVwAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Akuntansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Akuntansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Akuntansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Akuntansi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Akuntansi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private usu.widget.ButtonGlass btnAruskas;
    private usu.widget.ButtonGlass btnLaporan;
    private usu.widget.ButtonGlass btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jamVw;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass6;
    private usu.widget.glass.PanelGlass panelGlass7;
    private javax.swing.JLabel tglVw;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    public void setUser(String USER, String id) {
         //To change body of generated methods, choose Tools | Templates.
        user.setText(USER);
        setIdUser= id;
    }
   
}
