/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.mainInterface;

import com.jamtgl.Jam;
import com.jamtgl.Tgl;
import com.sia.ui.pengaman.fLogin;
import com.sia.ui.laporan.Laporan;
import com.sia.ui.master.Pengguna;
import com.sia.ui.master.*;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;


/**
 *
 * @author ARCH
 */
public class Master extends javax.swing.JFrame {
    GridBagLayout layout = new GridBagLayout();
    Pengguna p1;
    Produk pr;
    Laporan lp;
    supplier sp;
    Pelanggan pg;
    
    //Panel2 p2;
    /**
     * Creates new form NewJFrame
     */
    public Master() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(false);
        DynamicPanel.setLayout(layout);
        jamVw.setLayout(layout);
        tglVw.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
       
        //jam
        Jam jt = new Jam();
        jamVw.add(jt);
        jt.setVisible(true);
        jamVw.repaint();
        jamVw.revalidate();
        
        //tgl
        Tgl tgl = new Tgl();
        tglVw.add(tgl);
        tgl.setVisible(true);
        tglVw.repaint();
        tglVw.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGlass1 = new usu.widget.glass.PanelGlass();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        Pengguna = new usu.widget.ButtonGlass();
        btnProduk = new usu.widget.ButtonGlass();
        btnLaporan = new usu.widget.ButtonGlass();
        buttonGlass8 = new usu.widget.ButtonGlass();
        Pelanggan = new usu.widget.ButtonGlass();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        btnLogout = new usu.widget.ButtonGlass();
        jButton1 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        jButton2 = new javax.swing.JButton();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        jamVw = new javax.swing.JLabel();
        tglVw = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1365, 745));

        panelGlass1.setAlpha(1.0F);
        panelGlass1.setBackground(new java.awt.Color(255, 255, 255));
        panelGlass1.setMinimumSize(new java.awt.Dimension(1366, 745));
        panelGlass1.setPreferredSize(new java.awt.Dimension(1366, 745));
        panelGlass1.setRound(false);
        panelGlass1.setWarna(new java.awt.Color(51, 51, 51));
        panelGlass1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass2.setAlpha(0.0F);
        panelGlass2.setPreferredSize(new java.awt.Dimension(733, 493));
        panelGlass2.setRound(false);

        Pengguna.setBorder(null);
        Pengguna.setForeground(new java.awt.Color(255, 255, 255));
        Pengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnPengguna.png"))); // NOI18N
        Pengguna.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        Pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenggunaActionPerformed(evt);
            }
        });

        btnProduk.setBorder(null);
        btnProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnProduk.png"))); // NOI18N
        btnProduk.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdukActionPerformed(evt);
            }
        });

        btnLaporan.setBorder(null);
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnLaporan.png"))); // NOI18N
        btnLaporan.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        buttonGlass8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnSetting.png"))); // NOI18N
        buttonGlass8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass8ActionPerformed(evt);
            }
        });

        Pelanggan.setBorder(null);
        Pelanggan.setForeground(new java.awt.Color(255, 255, 255));
        Pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnPelanggan.png"))); // NOI18N
        Pelanggan.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        Pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGlass8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGlass8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );

        panelGlass1.add(panelGlass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, 80));

        panelGlass4.setAlpha(0.0F);
        panelGlass4.setRound(false);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btnLogout.png"))); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass4Layout = new javax.swing.GroupLayout(panelGlass4);
        panelGlass4.setLayout(panelGlass4Layout);
        panelGlass4Layout.setHorizontalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass4Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panelGlass4Layout.setVerticalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass4Layout.createSequentialGroup()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        panelGlass1.add(panelGlass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1164, -1, 200, 100));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelGlass1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        DynamicPanel.setBackground(new java.awt.Color(102, 102, 102));
        DynamicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DynamicPanel.setMinimumSize(new java.awt.Dimension(1366, 650));
        DynamicPanel.setPreferredSize(new java.awt.Dimension(1366, 650));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1364, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );

        panelGlass1.add(DynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASTER");
        panelGlass1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        panelGlass6.setBackground(new java.awt.Color(0, 0, 0));
        panelGlass6.setOpaque(true);
        panelGlass6.setRound(false);
        panelGlass6.setWarna(new java.awt.Color(6, 49, 122));

        javax.swing.GroupLayout panelGlass6Layout = new javax.swing.GroupLayout(panelGlass6);
        panelGlass6.setLayout(panelGlass6Layout);
        panelGlass6Layout.setHorizontalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        panelGlass6Layout.setVerticalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelGlass1.add(panelGlass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1370, 10));

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelGlass1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        panelGlass7.setBackground(new java.awt.Color(51, 51, 51));
        panelGlass7.setOpaque(true);
        panelGlass7.setRound(false);

        jamVw.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jamVw.setForeground(new java.awt.Color(255, 255, 255));
        jamVw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jamVw.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jamVwAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tglVw.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tglVw.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelGlass7Layout = new javax.swing.GroupLayout(panelGlass7);
        panelGlass7.setLayout(panelGlass7Layout);
        panelGlass7Layout.setHorizontalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jamVw, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass7Layout.setVerticalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglVw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGlass7Layout.createSequentialGroup()
                        .addComponent(jamVw, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelGlass1.add(panelGlass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 290, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlass1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGlass1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenggunaActionPerformed
        // TODO add your handling code here:
          //remove panel
        DynamicPanel.removeAll();
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        
        //adding panel
        p1 = new Pengguna();
        DynamicPanel.add(p1);
        p1.setVisible(true);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
    }//GEN-LAST:event_PenggunaActionPerformed

    private void btnProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdukActionPerformed
        // TODO add your handling code here:
        //remove
        DynamicPanel.removeAll();
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        
        //adding panel
        pr = new Produk();
        DynamicPanel.add(pr);
        pr.setVisible(true);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
    }//GEN-LAST:event_btnProdukActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        fLogin login = new fLogin();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void buttonGlass8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass8ActionPerformed
        // TODO add your handling code here:
        //  new koperasi.setting().setVisible(true);
    }//GEN-LAST:event_buttonGlass8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Akuntansi().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        //remove panel
        DynamicPanel.removeAll();
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        
        //adding panel
        lp = new Laporan();
        DynamicPanel.add(lp);
        lp.setVisible(true);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
    
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Transaksi().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelangganActionPerformed
        // TODO add your handling code here:
         //remove panel
        DynamicPanel.removeAll();
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        
        //adding panel
        pg = new Pelanggan();
        DynamicPanel.add(pg);
        pg.setVisible(true);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
    }//GEN-LAST:event_PelangganActionPerformed

    private void jamVwAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jamVwAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jamVwAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private usu.widget.ButtonGlass Pelanggan;
    private usu.widget.ButtonGlass Pengguna;
    private usu.widget.ButtonGlass btnLaporan;
    private usu.widget.ButtonGlass btnLogout;
    private usu.widget.ButtonGlass btnProduk;
    private usu.widget.ButtonGlass buttonGlass8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jamVw;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass6;
    private usu.widget.glass.PanelGlass panelGlass7;
    private javax.swing.JLabel tglVw;
    // End of variables declaration//GEN-END:variables
}
