/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.mainInterface;

import com.sia.ui.transaksi.*;
//import com.sia.ui.aruskas.HelpProduk;
import com.sia.ui.pengaman.fLogin;
import javax.swing.JFrame;

/**
 *
 * @author ARCH
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public Transaksi() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setAlwaysOnTop(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        jDate = new javax.swing.JLabel();
        jTgl = new javax.swing.JLabel();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        jRp = new javax.swing.JLabel();
        jBayar = new javax.swing.JLabel();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        total = new javax.swing.JLabel();
        namabarang = new javax.swing.JLabel();
        hargabarang = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        qty1 = new javax.swing.JTextField();
        qty2 = new javax.swing.JTextField();
        qty3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        btnDel = new usu.widget.ButtonGlass();
        btnAdd = new usu.widget.ButtonGlass();
        btnPending = new usu.widget.ButtonGlass();
        btnRefresh1 = new usu.widget.ButtonGlass();
        btnReprint = new usu.widget.ButtonGlass();
        panelGlass8 = new usu.widget.glass.PanelGlass();
        namabarang1 = new javax.swing.JLabel();
        hargabarang1 = new javax.swing.JLabel();
        hargabarang2 = new javax.swing.JLabel();
        hargabarang4 = new javax.swing.JLabel();
        hargabarang5 = new javax.swing.JLabel();
        hargabarang6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        produk = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        BayarCash = new javax.swing.JMenuItem();
        BayarKartu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Pembelian = new javax.swing.JMenu();
        Pemebelian = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        saldo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGlass1.setAlpha(1.0F);
        panelGlass1.setBackground(new java.awt.Color(255, 255, 255));
        panelGlass1.setMinimumSize(new java.awt.Dimension(0, 0));
        panelGlass1.setPreferredSize(new java.awt.Dimension(1365, 745));
        panelGlass1.setRound(false);
        panelGlass1.setWarna(new java.awt.Color(102, 102, 102));
        panelGlass1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass5.setRound(false);

        jDate.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jDate.setForeground(new java.awt.Color(255, 255, 255));
        jDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDate.setText("23-07-2015");
        jDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTgl.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jTgl.setForeground(new java.awt.Color(255, 255, 255));
        jTgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTgl.setText("23:45");
        jTgl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelGlass5Layout = new javax.swing.GroupLayout(panelGlass5);
        panelGlass5.setLayout(panelGlass5Layout);
        panelGlass5Layout.setHorizontalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        panelGlass5Layout.setVerticalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass1.add(panelGlass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 60));

        panelGlass6.setAlpha(0.08F);
        panelGlass6.setBackground(new java.awt.Color(255, 255, 255));
        panelGlass6.setOpaque(true);

        jRp.setBackground(new java.awt.Color(51, 51, 51));
        jRp.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jRp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRp.setText("RP");

        jBayar.setBackground(new java.awt.Color(51, 51, 51));
        jBayar.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        jBayar.setText("45,234,211,980");

        javax.swing.GroupLayout panelGlass6Layout = new javax.swing.GroupLayout(panelGlass6);
        panelGlass6.setLayout(panelGlass6Layout);
        panelGlass6Layout.setHorizontalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRp, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        panelGlass6Layout.setVerticalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBayar)
                    .addComponent(jRp, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelGlass1.add(panelGlass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 670, 140));

        panelGlass7.setRound(false);

        total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total.setForeground(new java.awt.Color(51, 51, 51));
        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("HARGA TOTAL");
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        total.setOpaque(true);

        namabarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namabarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namabarang.setText("NAMA BARANG");
        namabarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        namabarang.setOpaque(true);

        hargabarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargabarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargabarang.setText("HARGA BARANG");
        hargabarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hargabarang.setOpaque(true);

        kode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kode.setText("NMA09828687276783");
        kode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qty1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty1ActionPerformed(evt);
            }
        });

        qty2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qty2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty2ActionPerformed(evt);
            }
        });

        qty3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qty3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        qty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass7Layout = new javax.swing.GroupLayout(panelGlass7);
        panelGlass7.setLayout(panelGlass7Layout);
        panelGlass7Layout.setHorizontalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qty2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qty3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qty1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass7Layout.setVerticalGroup(
            panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(qty2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(qty3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(qty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(hargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelGlass1.add(panelGlass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1350, 30));

        jTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Qty", "Dis", "Ukuran", "Nama Barang", "Harga Barang", "Harga Total"
            }
        ));
        jTable.setSelectionForeground(new java.awt.Color(51, 153, 255));
        jTable.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(jTable);

        panelGlass1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 1340, 400));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ukr");
        panelGlass1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KODE");
        panelGlass1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        panelGlass3.setAlpha(0.0F);
        panelGlass3.setRound(false);

        btnDel.setForeground(new java.awt.Color(255, 255, 255));
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_delete1.png"))); // NOI18N
        btnDel.setText("Hapus");
        btnDel.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnDel.setPreferredSize(new java.awt.Dimension(117, 41));
        btnDel.setRoundRect(true);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_new1.png"))); // NOI18N
        btnAdd.setText("Tambah");
        btnAdd.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnAdd.setRoundRect(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnPending.setForeground(new java.awt.Color(255, 255, 255));
        btnPending.setText("Pending");
        btnPending.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnPending.setPreferredSize(new java.awt.Dimension(117, 41));
        btnPending.setRoundRect(true);
        btnPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendingActionPerformed(evt);
            }
        });

        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_refresh1.png"))); // NOI18N
        btnRefresh1.setText("Refresh");
        btnRefresh1.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnRefresh1.setPreferredSize(new java.awt.Dimension(117, 41));
        btnRefresh1.setRoundRect(true);
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        btnReprint.setForeground(new java.awt.Color(255, 255, 255));
        btnReprint.setText("RePrint");
        btnReprint.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnReprint.setPreferredSize(new java.awt.Dimension(117, 41));
        btnReprint.setRoundRect(true);
        btnReprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass3Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPending, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReprint, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass3Layout.createSequentialGroup()
                    .addContainerGap(354, Short.MAX_VALUE)
                    .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(169, 169, 169)))
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addComponent(btnPending, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReprint, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGlass3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelGlass1.add(panelGlass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 640, -1));

        panelGlass8.setRound(false);

        namabarang1.setBackground(new java.awt.Color(153, 153, 153));
        namabarang1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namabarang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namabarang1.setText("F1 | Produk");
        namabarang1.setOpaque(true);

        hargabarang1.setBackground(new java.awt.Color(153, 153, 153));
        hargabarang1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargabarang1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargabarang1.setText("F2 | Bayar Cash");
        hargabarang1.setOpaque(true);

        hargabarang2.setBackground(new java.awt.Color(153, 153, 153));
        hargabarang2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargabarang2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargabarang2.setText("F3 | Bayar Kartu");
        hargabarang2.setOpaque(true);

        hargabarang4.setBackground(new java.awt.Color(153, 153, 153));
        hargabarang4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargabarang4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargabarang4.setText("F4 | Pembelian");
        hargabarang4.setOpaque(true);

        hargabarang5.setBackground(new java.awt.Color(153, 153, 153));
        hargabarang5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargabarang5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargabarang5.setText("F5 | Saldo Insidentil");
        hargabarang5.setOpaque(true);

        hargabarang6.setBackground(new java.awt.Color(153, 153, 153));
        hargabarang6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargabarang6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargabarang6.setText("Esc | Keluar");
        hargabarang6.setOpaque(true);

        javax.swing.GroupLayout panelGlass8Layout = new javax.swing.GroupLayout(panelGlass8);
        panelGlass8.setLayout(panelGlass8Layout);
        panelGlass8Layout.setHorizontalGroup(
            panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(namabarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargabarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hargabarang2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hargabarang4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hargabarang5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hargabarang6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(521, Short.MAX_VALUE))
        );
        panelGlass8Layout.setVerticalGroup(
            panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass8Layout.createSequentialGroup()
                .addGroup(panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namabarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargabarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargabarang2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargabarang4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargabarang5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargabarang6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        panelGlass1.add(panelGlass8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QTY");
        panelGlass1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelGlass1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, -1, -1));

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelGlass1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DIS");
        panelGlass1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelGlass1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 140, 20));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setText("Help");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.add(jSeparator2);

        produk.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        produk.setText("Produk");
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });
        jMenu1.add(produk);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Bayar");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        BayarCash.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        BayarCash.setText("Bayar Cash");
        BayarCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarCashActionPerformed(evt);
            }
        });
        jMenu7.add(BayarCash);

        BayarKartu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        BayarKartu.setText("Bayar Kartu");
        BayarKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarKartuActionPerformed(evt);
            }
        });
        jMenu7.add(BayarKartu);
        jMenu7.add(jSeparator1);

        jMenuBar1.add(jMenu7);

        Pembelian.setText("Pembelian");
        Pembelian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Pemebelian.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        Pemebelian.setText("Pembelian");
        Pemebelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PemebelianActionPerformed(evt);
            }
        });
        Pembelian.add(Pemebelian);

        jMenuBar1.add(Pembelian);

        jMenu2.setText("Saldo Insidentil");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        saldo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        saldo.setText("Saldo");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        jMenu2.add(saldo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Submit Transaksi");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem2.setText("Submit Transaksi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1365, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void BayarCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarCashActionPerformed
        // TODO add your handling code here:
        new Bayar().setVisible(true);
    }//GEN-LAST:event_BayarCashActionPerformed

    private void BayarKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarKartuActionPerformed
        // TODO add your handling code here:
        new BayarKartu().setVisible(true);
    }//GEN-LAST:event_BayarKartuActionPerformed

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
        // TODO add your handling code here:
       new HelpProduk().setVisible(true);
    }//GEN-LAST:event_produkActionPerformed

    private void qty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty1ActionPerformed

    private void qty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty2ActionPerformed

    private void qty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty3ActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        //        try{
            //            String id=String.valueOf(tblpengguna.getValueAt(tblpengguna.getSelectedRow(), 0));
            //            if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                //                con.queryDelete("tb_pengguna", "NoAnggota="+id);
                //                clear();
                //            }else{
                //                return;
                //            }
            //        }catch(Exception e){
            //            System.out.println(e);
            //        }
        //        loadTable();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        //  err_msg.setVisible(true);
        //  createPengguna();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingActionPerformed
        // TODO add your handling code here:
        // loadTable();
        // clear();
    }//GEN-LAST:event_btnPendingActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void btnReprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReprintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReprintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        new Master().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Akuntansi().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
        new saldoInsedintil().setVisible(true);
    }//GEN-LAST:event_saldoActionPerformed

    private void PemebelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PemebelianActionPerformed
        // TODO add your handling code here:
        new Pembelian().setVisible(true);
    }//GEN-LAST:event_PemebelianActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
       this.dispose();
        fLogin login = new fLogin();
        login.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BayarCash;
    private javax.swing.JMenuItem BayarKartu;
    private javax.swing.JMenu Pembelian;
    private javax.swing.JMenuItem Pemebelian;
    private usu.widget.ButtonGlass btnAdd;
    private usu.widget.ButtonGlass btnDel;
    private usu.widget.ButtonGlass btnPending;
    private usu.widget.ButtonGlass btnRefresh1;
    private usu.widget.ButtonGlass btnReprint;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel hargabarang;
    private javax.swing.JLabel hargabarang1;
    private javax.swing.JLabel hargabarang2;
    private javax.swing.JLabel hargabarang4;
    private javax.swing.JLabel hargabarang5;
    private javax.swing.JLabel hargabarang6;
    private javax.swing.JLabel jBayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel jRp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jTgl;
    private javax.swing.JTextField kode;
    private javax.swing.JLabel namabarang;
    private javax.swing.JLabel namabarang1;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    private usu.widget.glass.PanelGlass panelGlass7;
    private usu.widget.glass.PanelGlass panelGlass8;
    private javax.swing.JMenuItem produk;
    private javax.swing.JTextField qty1;
    private javax.swing.JTextField qty2;
    private javax.swing.JTextField qty3;
    private javax.swing.JMenuItem saldo;
    private javax.swing.JLabel total;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    public void setUser(String USER, String id) {
        //To change body of generated methods, choose Tools | Templates.
        user.setText(USER);
        String setIdUser=id;
    }
}
