/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.aruskas;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author ARCH
 */
public class Aruskas extends javax.swing.JPanel {
    GridBagLayout layout = new GridBagLayout();
    SaldoPems pm;
    Pembelian pk;
    ProAruskas pa;
    String setIdUser;
    //Panel2 p2;
    
    /**
     * Creates new form Laporan
     */
    public Aruskas(String Id) {
        initComponents();
        setIdUser= Id;
        DynamicPanelpanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DynamicPanelpanel = new javax.swing.JPanel();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        label1 = new usu.widget.Label();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        btnpengeluaran = new usu.widget.ButtonGlass();
        btnProyeksiAruskas = new usu.widget.ButtonGlass();
        btnMasuk = new usu.widget.ButtonGlass();

        setBackground(java.awt.Color.darkGray);
        setPreferredSize(new java.awt.Dimension(1366, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DynamicPanelpanel.setOpaque(false);
        DynamicPanelpanel.setPreferredSize(new java.awt.Dimension(1366, 590));

        javax.swing.GroupLayout DynamicPanelpanelLayout = new javax.swing.GroupLayout(DynamicPanelpanel);
        DynamicPanelpanel.setLayout(DynamicPanelpanelLayout);
        DynamicPanelpanelLayout.setHorizontalGroup(
            DynamicPanelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        DynamicPanelpanelLayout.setVerticalGroup(
            DynamicPanelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        add(DynamicPanelpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 582));

        panelGlass6.setAlpha(0.0F);
        panelGlass6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        panelGlass6.setPreferredSize(new java.awt.Dimension(264, 54));
        panelGlass6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("ARUS KAS");
        label1.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        panelGlass6.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 30));

        add(panelGlass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1092, 0, -1, 40));

        panelGlass5.setAlpha(1.0F);
        panelGlass5.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass5.setRound(false);
        panelGlass5.setToolTipText("");

        btnpengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        btnpengeluaran.setBorder(null);
        btnpengeluaran.setText("Pengeluaran");
        btnpengeluaran.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        btnpengeluaran.setOpaque(true);
        btnpengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpengeluaranActionPerformed(evt);
            }
        });

        btnProyeksiAruskas.setBackground(new java.awt.Color(255, 255, 255));
        btnProyeksiAruskas.setBorder(null);
        btnProyeksiAruskas.setText("Proyeksi");
        btnProyeksiAruskas.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        btnProyeksiAruskas.setOpaque(true);
        btnProyeksiAruskas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProyeksiAruskasActionPerformed(evt);
            }
        });

        btnMasuk.setBackground(java.awt.Color.white);
        btnMasuk.setBorder(null);
        btnMasuk.setText("Saldo");
        btnMasuk.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        btnMasuk.setOpaque(true);
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass5Layout = new javax.swing.GroupLayout(panelGlass5);
        panelGlass5.setLayout(panelGlass5Layout);
        panelGlass5Layout.setHorizontalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addComponent(btnpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProyeksiAruskas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass5Layout.setVerticalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addGroup(panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProyeksiAruskas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        add(panelGlass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 42));
    }// </editor-fold>//GEN-END:initComponents

    private void btnpengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpengeluaranActionPerformed
        // TODO add your handling code here:
        DynamicPanelpanel.removeAll();
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        //adding panel
        pk = new Pembelian(setIdUser);
        DynamicPanelpanel.add(pk);
        pk.setVisible(true);
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        btnMasuk.setForeground(Color.BLACK);
        btnMasuk.setBackground(Color.WHITE);
        btnProyeksiAruskas.setForeground(Color.BLACK);
        btnProyeksiAruskas.setBackground(Color.WHITE);
        btnpengeluaran.setForeground(Color.WHITE);
        btnpengeluaran.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_btnpengeluaranActionPerformed

    private void btnProyeksiAruskasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProyeksiAruskasActionPerformed
        // TODO add your handling code here:
        DynamicPanelpanel.removeAll();
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        //adding panel
        pa = new ProAruskas(setIdUser);
        DynamicPanelpanel.add(pa);
        pa.setVisible(true);
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        btnMasuk.setForeground(Color.BLACK);
        btnMasuk.setBackground(Color.WHITE);
        btnProyeksiAruskas.setForeground(Color.WHITE);
        btnProyeksiAruskas.setBackground(Color.DARK_GRAY);
        btnpengeluaran.setForeground(Color.black);
        btnpengeluaran.setBackground(Color.white);
    }//GEN-LAST:event_btnProyeksiAruskasActionPerformed

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        DynamicPanelpanel.removeAll();
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        //adding panel
        pm = new SaldoPems(setIdUser);
        DynamicPanelpanel.add(pm);
        pm.setVisible(true);
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        btnMasuk.setForeground(Color.white);
        btnMasuk.setBackground(Color.DARK_GRAY);
        btnProyeksiAruskas.setForeground(Color.BLACK);
        btnProyeksiAruskas.setBackground(Color.WHITE);
        btnpengeluaran.setForeground(Color.black);
        btnpengeluaran.setBackground(Color.white);
    }//GEN-LAST:event_btnMasukActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanelpanel;
    private usu.widget.ButtonGlass btnMasuk;
    private usu.widget.ButtonGlass btnProyeksiAruskas;
    private usu.widget.ButtonGlass btnpengeluaran;
    private usu.widget.Label label1;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    // End of variables declaration//GEN-END:variables


}
