/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.aruskas;

import com.query.PemasukanQuery;
import com.query.PemsSaldoQuery;
import com.query.PendapatanQuery;
import com.query.PengeluaranQuery;
import com.query.SaldoQuery;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ARCH
 */
public class InsertSaldo extends javax.swing.JFrame {
  PengeluaranQuery pengQue;
    PemasukanQuery pemQue;
    SaldoQuery salQue;
    PendapatanQuery pendQue;
    PemsSaldoQuery pemsalQue;
    
    String setIdUser;
    /**
     * Creates new form InsertSaldo
     */
    public InsertSaldo() {
        initComponents();
        
        pengQue = new PengeluaranQuery() ;
        pemQue = new PemasukanQuery() ;
        salQue = new SaldoQuery();
        pendQue = new PendapatanQuery();
        pemsalQue = new PemsSaldoQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new usu.widget.glass.PanelGlass();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        btnSave = new usu.widget.ButtonGlass();
        jPanel2 = new javax.swing.JPanel();
        panelGlass20 = new usu.widget.glass.PanelGlass();
        jLabel13 = new javax.swing.JLabel();
        panelGlass36 = new usu.widget.glass.PanelGlass();
        isiSaldoSisaUsaha = new javax.swing.JFormattedTextField();
        btnOK = new usu.widget.ButtonGlass();
        panelGlass25 = new usu.widget.glass.PanelGlass();
        panelGlass37 = new usu.widget.glass.PanelGlass();
        isiTanggal = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setAlpha(1.0F);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.white));
        jPanel1.setPreferredSize(new java.awt.Dimension(675, 184));
        jPanel1.setRound(false);
        jPanel1.setWarna(new java.awt.Color(51, 51, 51));

        jCalendar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jCalendar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCalendar1MouseClicked(evt);
            }
        });
        jCalendar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCalendar1KeyReleased(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_save.png"))); // NOI18N
        btnSave.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnSave.setRoundRect(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        panelGlass20.setAlpha(1.0F);
        panelGlass20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass20.setRound(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Saldo");

        panelGlass36.setAlpha(1.0F);
        panelGlass36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass36.setRound(false);

        isiSaldoSisaUsaha.setBorder(null);
        isiSaldoSisaUsaha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiSaldoSisaUsaha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiSaldoSisaUsaha.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass36Layout = new javax.swing.GroupLayout(panelGlass36);
        panelGlass36.setLayout(panelGlass36Layout);
        panelGlass36Layout.setHorizontalGroup(
            panelGlass36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiSaldoSisaUsaha, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass36Layout.setVerticalGroup(
            panelGlass36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiSaldoSisaUsaha, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass20Layout = new javax.swing.GroupLayout(panelGlass20);
        panelGlass20.setLayout(panelGlass20Layout);
        panelGlass20Layout.setHorizontalGroup(
            panelGlass20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelGlass36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass20Layout.setVerticalGroup(
            panelGlass20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGlass36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnOK.setBackground(new java.awt.Color(0, 153, 255));
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnOK.setOpaque(true);
        btnOK.setRoundRect(true);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        panelGlass25.setAlpha(1.0F);
        panelGlass25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass25.setRound(false);

        panelGlass37.setAlpha(1.0F);
        panelGlass37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass37.setRound(false);

        isiTanggal.setBorder(null);
        isiTanggal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiTanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiTanggal.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass37Layout = new javax.swing.GroupLayout(panelGlass37);
        panelGlass37.setLayout(panelGlass37Layout);
        panelGlass37Layout.setHorizontalGroup(
            panelGlass37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass37Layout.setVerticalGroup(
            panelGlass37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass25Layout = new javax.swing.GroupLayout(panelGlass25);
        panelGlass25.setLayout(panelGlass25Layout);
        panelGlass25Layout.setHorizontalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlass37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGlass25Layout.setVerticalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlass37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, Short.MAX_VALUE))
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(413, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        if(isiSaldoSisaUsaha.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Isikan Nominal Saldo!! Saldo Kosong");
        }else{
            SimpleDateFormat ft,ftt;
            ft = new SimpleDateFormat("yyyy-MM-dd");
            String date = ft.format(jCalendar1.getDate());
            save();
        }
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat ft,ftt;
        ft = new SimpleDateFormat("yyyy-MM-dd");
        String date = ft.format(jCalendar1.getDate());
        if(isiSaldoSisaUsaha.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Isikan Nominal Saldo!! Saldo Kosong");
        }else{
            okAction();
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void jCalendar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalendar1MouseClicked
        // TODO add your handling code here:
//        SimpleDateFormat ft,ftt;
//        ft = new SimpleDateFormat("yyyy-MM-dd");
//        String date = ft.format(jCalendar1.getDate());
//        System.out.println(date);
    }//GEN-LAST:event_jCalendar1MouseClicked

    private void jCalendar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCalendar1KeyReleased
        // TODO add your handling code here:
        SimpleDateFormat ft,ftt;
        ft = new SimpleDateFormat("yyyy-MM-dd");
        String date = ft.format(jCalendar1.getDate());
        System.out.println(date);
    }//GEN-LAST:event_jCalendar1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertSaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btnOK;
    private usu.widget.ButtonGlass btnSave;
    private javax.swing.JFormattedTextField isiSaldoSisaUsaha;
    private javax.swing.JFormattedTextField isiTanggal;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel13;
    private usu.widget.glass.PanelGlass jPanel1;
    private javax.swing.JPanel jPanel2;
    private usu.widget.glass.PanelGlass panelGlass20;
    private usu.widget.glass.PanelGlass panelGlass25;
    private usu.widget.glass.PanelGlass panelGlass36;
    private usu.widget.glass.PanelGlass panelGlass37;
    // End of variables declaration//GEN-END:variables
    
    public void save(){
        SimpleDateFormat ft,ftt;
            ft = new SimpleDateFormat("yyyy-MM-dd");
            String date = ft.format(jCalendar1.getDate());
            pemQue.insertInto(isiSaldoSisaUsaha,date);//beluuuuuum
            JOptionPane.showMessageDialog(this, "Saldo Berhasil Disimpan untuk Tanggal "+date+"");
    }
    
    public void okAction(){
        SimpleDateFormat ft,ftt;
        ft = new SimpleDateFormat("yyyy-MM-dd");
        String date = ft.format(jCalendar1.getDate());
        String bay = String.valueOf(isiSaldoSisaUsaha.getValue());
        isiSaldoSisaUsaha.setText("");
        isiTanggal.setText(date);
        salQue.viewTotalSld(date, isiSaldoSisaUsaha);
        if(!isiSaldoSisaUsaha.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Saldo tanggal "+date+" sudah terisi");
            isiSaldoSisaUsaha.setText(bay);
            isiTanggal.setText("");
        } else {
            isiTanggal.setText(date);
            isiSaldoSisaUsaha.setText(bay);
            salQue.insertInto(isiSaldoSisaUsaha, date);//oke
            pendQue.insertInto(date);//oke
            pengQue.insertInto(date);//oke
            pemsalQue.insertStat(date,setIdUser,isiSaldoSisaUsaha);
        }
    }

    public void setUser(String USER, String id) {
       //To change body of generated methods, choose Tools | Templates.
        setIdUser = id;
    }

    void callUser(String setId) {
         //To change body of generated methods, choose Tools | Templates.
        setIdUser=setId;
    }

}
