/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.aruskas;

import com.service.*;
import com.query.*;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARCH
 */
public class Pendapatan extends javax.swing.JPanel {
GridBagLayout layout = new GridBagLayout();

PemsSaldoQuery prodQue;
SaldoQuery saldoQue;
PembelianQuery pengeQue;
PemasukanQuery pemQue;
SaldoService saldoServ;

DefaultTableModel model;
java.util.Date tglSekarang = new java.util.Date();
    
    private SimpleDateFormat smpdt = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
    private String tanggal = smpdt.format(tglSekarang);

    /**
     * Creates new form pembukuanMasuk
     */
    public Pendapatan() {
        initComponents();
          //construct query
        tglVw.setText(tanggal);
        prodQue = new PemsSaldoQuery();
        saldoQue = new SaldoQuery();
        pemQue = new PemasukanQuery();
        model = new DefaultTableModel();
        //BynganNom.setText("0");

       //contruct metode matematika
        saldoServ = new SaldoService();
        //contruct tanggal
        tglVw.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
       // c.gridx = 0;
        //c.gridy = 0;
    
        //menampilkan data
        model.addColumn("Id");
        model.addColumn("Tanggal");
        model.addColumn("Nama Petugas");
        model.addColumn("Saldo Tambahan");
        model.addColumn("Status Saldo");
        tabelTransaksi.setModel(model);
        loadTabel();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        err_msg1 = new usu.widget.glass.PanelGlass();
        err_msg = new usu.widget.Label();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        panelGlass23 = new usu.widget.glass.PanelGlass();
        panelGlass27 = new usu.widget.glass.PanelGlass();
        isiTotalSaldo = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        btnDel = new usu.widget.ButtonGlass();
        btnEdit = new usu.widget.ButtonGlass();
        btnAdd = new usu.widget.ButtonGlass();
        btnRefresh = new usu.widget.ButtonGlass();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        btnSearch1 = new usu.widget.ButtonGlass();
        txtSearch = new javax.swing.JTextField();
        panelGlass8 = new usu.widget.glass.PanelGlass();
        tglVw = new javax.swing.JLabel();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        idVw = new javax.swing.JLabel();
        idBtn = new javax.swing.JLabel();
        idVw2 = new javax.swing.JLabel();
        Nominal = new javax.swing.JLabel();
        UpdSldo1 = new javax.swing.JLabel();
        BynganNom = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(22, 73, 154));
        setMinimumSize(new java.awt.Dimension(1366, 590));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1366, 590));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 590));

        err_msg1.setRound(false);

        err_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        err_msg.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout err_msg1Layout = new javax.swing.GroupLayout(err_msg1);
        err_msg1.setLayout(err_msg1Layout);
        err_msg1Layout.setHorizontalGroup(
            err_msg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(err_msg1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(err_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        err_msg1Layout.setVerticalGroup(
            err_msg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(err_msg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        panelGlass5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass5.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass5.setRound(false);

        panelGlass23.setAlpha(1.0F);
        panelGlass23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass23.setRound(false);

        panelGlass27.setAlpha(1.0F);
        panelGlass27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass27.setRound(false);

        isiTotalSaldo.setBorder(null);
        isiTotalSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiTotalSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiTotalSaldo.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass27Layout = new javax.swing.GroupLayout(panelGlass27);
        panelGlass27.setLayout(panelGlass27Layout);
        panelGlass27Layout.setHorizontalGroup(
            panelGlass27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTotalSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass27Layout.setVerticalGroup(
            panelGlass27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTotalSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Total Pendapatan");

        javax.swing.GroupLayout panelGlass23Layout = new javax.swing.GroupLayout(panelGlass23);
        panelGlass23.setLayout(panelGlass23Layout);
        panelGlass23Layout.setHorizontalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass23Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass23Layout.setVerticalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass23Layout.createSequentialGroup()
                .addGroup(panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGlass5Layout = new javax.swing.GroupLayout(panelGlass5);
        panelGlass5.setLayout(panelGlass5Layout);
        panelGlass5Layout.setHorizontalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass5Layout.setVerticalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass3.setAlpha(0.0F);
        panelGlass3.setRound(false);

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_delete.png"))); // NOI18N
        btnDel.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnDel.setPreferredSize(new java.awt.Dimension(117, 41));
        btnDel.setRoundRect(true);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_edit.png"))); // NOI18N
        btnEdit.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(117, 41));
        btnEdit.setRoundRect(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_new.png"))); // NOI18N
        btnAdd.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnAdd.setRoundRect(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_refresh.png"))); // NOI18N
        btnRefresh.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(117, 41));
        btnRefresh.setRoundRect(true);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Saldo", "Nominal Saldo", "Keterangan"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        panelGlass4.setAlpha(1.0F);
        panelGlass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass4.setRound(false);

        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btn_search.png"))); // NOI18N
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGlass4Layout = new javax.swing.GroupLayout(panelGlass4);
        panelGlass4.setLayout(panelGlass4Layout);
        panelGlass4Layout.setHorizontalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass4Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass4Layout.setVerticalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSearch1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );

        panelGlass8.setBackground(new java.awt.Color(102, 102, 102));
        panelGlass8.setOpaque(true);
        panelGlass8.setRound(false);

        tglVw.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tglVw.setForeground(new java.awt.Color(255, 255, 255));
        tglVw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tglVw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        javax.swing.GroupLayout panelGlass8Layout = new javax.swing.GroupLayout(panelGlass8);
        panelGlass8.setLayout(panelGlass8Layout);
        panelGlass8Layout.setHorizontalGroup(
            panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelGlass8Layout.setVerticalGroup(
            panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelGlass6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass6.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass6.setRound(false);

        idVw2.setText("ID.SALDO");

        Nominal.setText("Nominal");

        UpdSldo1.setText("ID.Button");

        BynganNom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout panelGlass6Layout = new javax.swing.GroupLayout(panelGlass6);
        panelGlass6.setLayout(panelGlass6Layout);
        panelGlass6Layout.setHorizontalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass6Layout.createSequentialGroup()
                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGlass6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BynganNom, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(idVw2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idVw, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(idBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGlass6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UpdSldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(132, Short.MAX_VALUE)))
        );
        panelGlass6Layout.setVerticalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass6Layout.createSequentialGroup()
                        .addComponent(idVw2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(idVw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BynganNom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGlass6Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(Nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(UpdSldo1)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(err_msg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelGlass5, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelGlass6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(430, 430, 430)
                .addComponent(panelGlass8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(err_msg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelGlass5, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(panelGlass6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)))
                    .addComponent(panelGlass8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadTabel();
        clear();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        // TODO add your handling code here:
       tabelMouseAction();
        //        MatSaldo();
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        //        // TODO add your handling code here:
                ssearchAction();
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
                ssearchAction();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        idBtn.setText("1");
        tampilBtn();
        clear();
//        addAction();
//        loadTabel();
//        clear();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        idBtn.setText("2");
        tampilBtn();
        //        tampilMatSaldo();
        //        loadTabel();
        //        editAction();
        //        upteSaldo();
        //        clear();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        idBtn.setText("3");
        tampilBtn();
        //        tampilMatSaldo();
        //        loadTabel();
        //        upteSaldo();
        //        clear();
    }//GEN-LAST:event_btnDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField BynganNom;
    private javax.swing.JLabel Nominal;
    private javax.swing.JLabel UpdSldo1;
    private usu.widget.ButtonGlass btnAdd;
    private usu.widget.ButtonGlass btnDel;
    private usu.widget.ButtonGlass btnEdit;
    private usu.widget.ButtonGlass btnRefresh;
    private usu.widget.ButtonGlass btnSearch1;
    private usu.widget.Label err_msg;
    private usu.widget.glass.PanelGlass err_msg1;
    private javax.swing.JLabel idBtn;
    private javax.swing.JLabel idVw;
    private javax.swing.JLabel idVw2;
    private javax.swing.JFormattedTextField isiTotalSaldo;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private usu.widget.glass.PanelGlass panelGlass23;
    private usu.widget.glass.PanelGlass panelGlass27;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    private usu.widget.glass.PanelGlass panelGlass8;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JLabel tglVw;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public void clear(){
        //err_msg.setText("");
       
        BynganNom.setText("");
        idBtn.setText("");

        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDel.setEnabled(true);
    } 
    
    private void loadTabel(){
        List<String[]> result = prodQue.viewSaldoTambahan(tglVw);
        String TGL_SALDO;
        TGL_SALDO = tglVw.getText().trim();
        saldoQue.viewTotalSaldo(tglVw,isiTotalSaldo);
       
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        tabelTransaksi.setModel(model);
        for(int i = 0; i < result.size();i++){
            model.addRow(result.get(i));
        }
        tabelTransaksi.repaint();
        model.fireTableDataChanged();
        clear();
    }
    private void addAction() {
        /**sebelum melakukan add
         * kondisikan memilih input dan keterangan
        */ 
//        if(isiSaldo.getText().isEmpty()){
//            if(isiTotalSaldo.getText().isEmpty()){
//                JOptionPane.showMessageDialog(this, "Isikan Nominal Saldo!! Saldo Hari ini Kosong");
//            } else{
//                JOptionPane.showMessageDialog(this, "Isikan Nominal Saldo");
//            }
//        } else{
//            String isiSldo = String.valueOf(isiSaldo.getValue());
//            BigDecimal isiSld = new BigDecimal(isiSldo);
//            if(isiSld.compareTo(BigDecimal.ZERO)>0){
//                String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
//                    BigDecimal nomSldo = new BigDecimal(isiTtlSaldo);
//                if(!isiTotalSaldo.getText().isEmpty()){
//                    if(nomSldo.equals(BigDecimal.ZERO)){
//                        if(JOptionPane.showConfirmDialog(this, "Masukkan Saldo dulu!! Generate angka 1", "Peringatan", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION){
//                           isiTotalSaldo.setText("1");
//                           clear();
//                           saldoQue.editTotalSaldoUsaha(tglVw, isiTotalSaldo);
//                        }
//                    }else{
//                        if(isiKeterangan.getSelectedItem()!="saldo tambahan"){//harus sama persis
//                            JOptionPane.showMessageDialog(this, " Ganti Status Saldo 'Saldo Tambahan' atau 'Saldo Usaha Tambahan'!! ");
//                        }else{
//                           
//                            try{
//                                //prodQue.insertInto(tglVw,isiSaldo,isiKeterangan);
//                                 MatEdit();
//                                //System.out.println(""+isiTotalSaldo.getText());
//                                
//                                err_msg.setText(" Berhasil ditambahkan! ");
//                                err_msg.setForeground(Color.green);
//                            }
//                            catch(Exception e){
//                                err_msg.setText(" Gagal ditambahkan! ");
//                                err_msg.setForeground(Color.red);
//                            }  
//                        }
//                    }
//                }else {///fix gak usah pakai hitungan tambah untuk SALDO TAMBAHAN
//                    if(isiKeterangan.getSelectedItem()== "saldo tambahan"||isiKeterangan.getSelectedItem()== "saldo usaha tambahan"){
//                        JOptionPane.showMessageDialog(this, "Ganti Status Saldo 'Saldo Usaha'!!");
//                    } else if (isiKeterangan.getSelectedItem()== "saldo usaha"){
//                        try{
//                            insertMat();
//                            err_msg.setText(" Berhasil ditambahkan! ");
//                            err_msg.setForeground(Color.green);
//                        }
//                        catch(Exception e){
//                        err_msg.setText(" Gagal ditambahkan! ");
//                        err_msg.setForeground(Color.red);
//                        }
//                    }
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, " jangan Gunakan 0 ");
//                isiSaldo.setText("");
//            }
//            loadTabel();
//        }
//        
    }    
    
      private void editAction() {
     //To change body of generated methods, choose Tools | Templates.
        try {
            MatEdit();
            err_msg.setText("Berhasil diedit!");
            err_msg.setForeground(Color.green);
            //JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        catch(Exception ex){
        // Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
            err_msg.setText("Gagal diedit!");
            err_msg.setForeground(Color.red);
            //JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
        
    }  
    
    private void tampilBtn(){
        if (!idBtn.getText().isEmpty()){
            int Btn = Integer.parseInt(idBtn.getText());
            if(Btn==1){
                //JOptionPane.showMessageDialog(this, "1 ");
                //addAction();
                String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
                   // BigDecimal nomSldo = new BigDecimal(isiTtlSaldo);
                    System.out.println(""+isiTtlSaldo);    
            } else if (Btn==2){
                editAction();
                //JOptionPane.showMessageDialog(this, "3");
            } else if (Btn==3){
                JOptionPane.showMessageDialog(this, "3");
            }
           loadTabel(); 
        }
    }
    
    public void MatEdit(){
//         if(BynganNom.getText().isEmpty()){
//            String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
//            BigDecimal ttlSldo = new BigDecimal(isiTtlSaldo);
//            //double isiTtlSaldo = Double.parseDouble(isiTotalSaldo.getText());
//            System.out.println("isi total saldo"+isiTtlSaldo);
////            if(isiTtlSaldo==1){
//            if(ttlSldo.compareTo(BigDecimal.ONE) == 0){
//                isiTotalSaldo.setText("0");
//                saldoServ.addMat(isiSaldo, isiTotalSaldo,isiTtlPemasukan);
//            }else{
//                saldoServ.addMat(isiSaldo,isiTotalSaldo,isiTtlPemasukan);
//            }
//            prodQue.insertInto(tglVw,isiSaldo,isiKeterangan);
//        }else{
//            String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
//            BigDecimal ttlSldo = new BigDecimal(isiTtlSaldo);
//            String isiSld = String.valueOf(isiSaldo.getValue());
//            BigDecimal nomSld = new BigDecimal(isiSld);
//            String isiByg = String.valueOf(BynganNom.getValue());
//            BigDecimal nomByg = new BigDecimal(isiByg);
//            if(ttlSldo.compareTo(BigDecimal.ZERO) > 0){
//                if(!isiSaldo.getText().equals(BynganNom.getText())){
//                        saldoServ.editMat(isiSaldo,BynganNom,isiTotalSaldo,isiTtlPemasukan);
//                    
//                }else{
//                    if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
//                        saldoServ.delMat(isiSaldo, BynganNom,isiTotalSaldo,isiTtlPemasukan);
//                        prodQue.delete(idVw);
//                    }
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Joption ditambah saldo dulu");
//            }
//            prodQue.edit(idVw,isiSaldo);
//         }
//        if(BynganNom.getText().isEmpty()){
//            double isiTtlSaldo = Double.parseDouble(isiTotalSaldo.getText());
//            if(isiTtlSaldo==1){
//                isiTotalSaldo.setText("0");
//                saldoServ.addMat(isiSaldo, isiTotalSaldo);
//            }else{
//                saldoServ.addMat(isiSaldo,isiTotalSaldo);
//            }
//            prodQue.insertInto(tglVw,isiSaldo,isiKeterangan);
//        }else{
//            double isiTtlSaldo = Double.parseDouble(isiTotalSaldo.getText());
//            if(isiTtlSaldo>0){
//                double isiSld = Double.parseDouble(isiSaldo.getText());
//                double isiByg = Double.parseDouble(BynganNom.getText());
//                prodQue.edit(idVw,isiSaldo);
//                if(!isiSaldo.getText().equals(BynganNom.getText())){
//                    if(isiSld>isiByg){
//                        if(JOptionPane.showConfirmDialog(this, "Yakin merubah data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
//                            saldoServ.editTambah(isiSaldo,BynganNom,isiTotalSaldo);
//                        }
//                    }else{
//                        JOptionPane.showConfirmDialog(this, "isiSld<isiByg?", "Peringatan", JOptionPane.OK_CANCEL_OPTION);
//                        saldoServ.editKurang(isiSaldo,BynganNom,isiTotalSaldo);
//                    } 
//                } else{
//                    if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
//                        saldoServ.delMat(isiSaldo, BynganNom,isiTotalSaldo);
//                        prodQue.delete(idVw);
//                    }
//                }
//            } else{
//                JOptionPane.showMessageDialog(this, "Joption - ");
//            }
//        }
       // saldoQue.editTotalSaldoUsaha(tglVw,isiTotalSaldo);
       // pemQue.editPemasukan(tglVw, isiTtlPemasukan);
    }
    
    private void tabelMouseAction() {
       //To change body of generated methods, choose Tools | Templates.
        btnAdd.setEnabled(false);
       // isiKeterangan.setEnabled(false);
        int row = tabelTransaksi.getSelectedRow();
        idVw.setText(tabelTransaksi.getModel().getValueAt(row,0).toString());
        //isiSaldo.setText(tabelSaldo.getModel().getValueAt(row,3).toString());
        BynganNom.setText(tabelTransaksi.getModel().getValueAt(row,3).toString());
        
    }
    
//    private void insertMat(){
//        saldoQue.insertIntoSS(isiSaldo,tglVw);
//        prodQue.insertInto(tglVw,isiSaldo,isiKeterangan);
//        String NOM_SALDO = String.valueOf(isiSaldo.getValue());
//        if(isiTtlPemasukan.getText().isEmpty()){
//            pemQue.editPemasukan(tglVw,isiSaldo);
//        }else{
//             String TTL_PEM=String.valueOf(isiTtlPemasukan.getValue());
//            
//             BigDecimal TTLpem = new BigDecimal(TTL_PEM);
//             BigDecimal nomSaldo = new BigDecimal(NOM_SALDO);
//            
//             BigDecimal zzz = nomSaldo.add(TTLpem);
//                       
//             isiTtlPemasukan.setValue(zzz);  
//        }
//            pemQue.editPemasukan(tglVw,isiTtlPemasukan);
//    }
//    
     private void ssearchAction() {
       //To change body of generated methods, choose Tools | Templates.
            try{
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                tabelTransaksi.setModel(model);
                List<String[]> result=  prodQue.fcSelectCommand(txtSearch);
                String search;
                search = txtSearch.getText().trim();
                for(int i = 0; i < result.size();i++){
                     model.addRow(result.get(i));
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Pencarian tidak Ditemukan!!");
            }
    }
    
}
