/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.aruskas;

import com.print.ArusKasCtk;
import com.query.AruskasQuery;
import com.query.PemasukanQuery;
import com.query.PembelianQuery;
import com.query.PendapatanQuery;
import com.query.PengeluaranQuery;
import com.query.SaldoQuery;
import com.query.SubTransQuery;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ARCH
 */
public class ProAruskas extends javax.swing.JPanel {
    GridBagLayout layout = new GridBagLayout();
    java.util.Date tglSekarang = new java.util.Date();
    
    String idV,setIdUser;
    private SimpleDateFormat smpdt = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
    private String tanggal = smpdt.format(tglSekarang);
    
    PembelianQuery pembQue;
    PengeluaranQuery pengQue;
    PemasukanQuery pemQue;
    SaldoQuery salQue;
    PendapatanQuery pendQue;
    AruskasQuery arusQue;
    SubTransQuery subtQue;
    
    /// cetak
    ArusKasCtk cetPr;

    /**
     * Creates new form ProAruskas
     */
    public ProAruskas(String Id) {
        initComponents();
        setIdUser=Id;
        tglVw.setText(tanggal);
        tglVw.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        panelGjam.setVisible(false);
        
        pembQue = new PembelianQuery() ;
        pengQue = new PengeluaranQuery() ;
        pemQue = new PemasukanQuery() ;
        salQue = new SaldoQuery();
        pendQue = new PendapatanQuery();
        arusQue = new AruskasQuery();
        subtQue = new SubTransQuery();
        
        //cetak 
        cetPr = new ArusKasCtk();
        focus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proArus = new javax.swing.JPanel();
        panelGlass15 = new usu.widget.glass.PanelGlass();
        panelGlass8 = new usu.widget.glass.PanelGlass();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelGlass30 = new usu.widget.glass.PanelGlass();
        isiCash = new javax.swing.JFormattedTextField();
        panelGlass31 = new usu.widget.glass.PanelGlass();
        isiBankA = new javax.swing.JFormattedTextField();
        panelGlass32 = new usu.widget.glass.PanelGlass();
        isiBankB = new javax.swing.JFormattedTextField();
        panelGlass33 = new usu.widget.glass.PanelGlass();
        isiBankC = new javax.swing.JFormattedTextField();
        panelGlass25 = new usu.widget.glass.PanelGlass();
        jLabel19 = new javax.swing.JLabel();
        panelGlass36 = new usu.widget.glass.PanelGlass();
        isiTotalPendapatan1 = new javax.swing.JFormattedTextField();
        panelGlass18 = new usu.widget.glass.PanelGlass();
        jLabel11 = new javax.swing.JLabel();
        panelGlass28 = new usu.widget.glass.PanelGlass();
        isiTotalSaldo = new javax.swing.JFormattedTextField();
        panelGlass19 = new usu.widget.glass.PanelGlass();
        jLabel12 = new javax.swing.JLabel();
        panelGlass34 = new usu.widget.glass.PanelGlass();
        isiTotalPengeluaran = new javax.swing.JFormattedTextField();
        panelGlass21 = new usu.widget.glass.PanelGlass();
        jLabel14 = new javax.swing.JLabel();
        panelGlass38 = new usu.widget.glass.PanelGlass();
        isiSetoran = new javax.swing.JFormattedTextField();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        btnSubmit = new usu.widget.ButtonGlass();
        btnRefresh = new usu.widget.ButtonGlass();
        btnPrint = new usu.widget.ButtonGlass();
        panelGlass22 = new usu.widget.glass.PanelGlass();
        jLabel15 = new javax.swing.JLabel();
        panelGlass35 = new usu.widget.glass.PanelGlass();
        isiSisaPemasukan = new javax.swing.JFormattedTextField();
        panelGlass23 = new usu.widget.glass.PanelGlass();
        jLabel16 = new javax.swing.JLabel();
        panelGlass39 = new usu.widget.glass.PanelGlass();
        isiSaldoEsok = new javax.swing.JFormattedTextField();
        panelGlass26 = new usu.widget.glass.PanelGlass();
        jLabel18 = new javax.swing.JLabel();
        panelGlass40 = new usu.widget.glass.PanelGlass();
        isiTotalPemasukan = new javax.swing.JFormattedTextField();
        panelGjam = new usu.widget.glass.PanelGlass();
        tglVw = new javax.swing.JLabel();
        errmsg = new usu.widget.glass.PanelGlass();
        lblPesan = new usu.widget.Label();

        proArus.setBackground(java.awt.Color.darkGray);
        proArus.setForeground(new java.awt.Color(255, 255, 255));
        proArus.setMinimumSize(new java.awt.Dimension(1366, 590));
        proArus.setPreferredSize(new java.awt.Dimension(1366, 590));
        proArus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGlass15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass15.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass15.setRound(false);

        panelGlass8.setAlpha(1.0F);
        panelGlass8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass8.setRound(false);
        panelGlass8.setWarna(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Rincian");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Cash");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Bank A");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Bank B");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Bank C");

        panelGlass30.setAlpha(1.0F);
        panelGlass30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass30.setRound(false);

        isiCash.setEditable(false);
        isiCash.setBorder(null);
        isiCash.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiCash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiCash.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass30Layout = new javax.swing.GroupLayout(panelGlass30);
        panelGlass30.setLayout(panelGlass30Layout);
        panelGlass30Layout.setHorizontalGroup(
            panelGlass30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiCash, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass30Layout.setVerticalGroup(
            panelGlass30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiCash, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        panelGlass31.setAlpha(1.0F);
        panelGlass31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass31.setRound(false);

        isiBankA.setEditable(false);
        isiBankA.setBorder(null);
        isiBankA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiBankA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiBankA.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass31Layout = new javax.swing.GroupLayout(panelGlass31);
        panelGlass31.setLayout(panelGlass31Layout);
        panelGlass31Layout.setHorizontalGroup(
            panelGlass31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiBankA, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass31Layout.setVerticalGroup(
            panelGlass31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiBankA, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        panelGlass32.setAlpha(1.0F);
        panelGlass32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass32.setRound(false);

        isiBankB.setEditable(false);
        isiBankB.setBorder(null);
        isiBankB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiBankB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiBankB.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass32Layout = new javax.swing.GroupLayout(panelGlass32);
        panelGlass32.setLayout(panelGlass32Layout);
        panelGlass32Layout.setHorizontalGroup(
            panelGlass32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiBankB, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass32Layout.setVerticalGroup(
            panelGlass32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiBankB, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        panelGlass33.setAlpha(1.0F);
        panelGlass33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass33.setRound(false);

        isiBankC.setEditable(false);
        isiBankC.setBorder(null);
        isiBankC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiBankC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiBankC.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass33Layout = new javax.swing.GroupLayout(panelGlass33);
        panelGlass33.setLayout(panelGlass33Layout);
        panelGlass33Layout.setHorizontalGroup(
            panelGlass33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiBankC, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass33Layout.setVerticalGroup(
            panelGlass33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiBankC, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelGlass25.setAlpha(1.0F);
        panelGlass25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass25.setRound(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Total Pendapatan");

        panelGlass36.setAlpha(1.0F);
        panelGlass36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass36.setRound(false);

        isiTotalPendapatan1.setEditable(false);
        isiTotalPendapatan1.setBorder(null);
        isiTotalPendapatan1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiTotalPendapatan1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiTotalPendapatan1.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        isiTotalPendapatan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isiTotalPendapatanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelGlass36Layout = new javax.swing.GroupLayout(panelGlass36);
        panelGlass36.setLayout(panelGlass36Layout);
        panelGlass36Layout.setHorizontalGroup(
            panelGlass36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTotalPendapatan1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass36Layout.setVerticalGroup(
            panelGlass36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTotalPendapatan1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass25Layout = new javax.swing.GroupLayout(panelGlass25);
        panelGlass25.setLayout(panelGlass25Layout);
        panelGlass25Layout.setHorizontalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass25Layout.setVerticalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGlass36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass8Layout = new javax.swing.GroupLayout(panelGlass8);
        panelGlass8.setLayout(panelGlass8Layout);
        panelGlass8Layout.setHorizontalGroup(
            panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addComponent(panelGlass25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGlass8Layout.setVerticalGroup(
            panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass8Layout.createSequentialGroup()
                .addComponent(panelGlass25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass8Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelGlass8Layout.createSequentialGroup()
                        .addGroup(panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(panelGlass30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(panelGlass31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(panelGlass32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGlass8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(panelGlass33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        panelGlass18.setAlpha(1.0F);
        panelGlass18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass18.setRound(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Saldo");

        panelGlass28.setAlpha(1.0F);
        panelGlass28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass28.setRound(false);

        isiTotalSaldo.setEditable(false);
        isiTotalSaldo.setBorder(null);
        isiTotalSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiTotalSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiTotalSaldo.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        isiTotalSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isiTotalSaldoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelGlass28Layout = new javax.swing.GroupLayout(panelGlass28);
        panelGlass28.setLayout(panelGlass28Layout);
        panelGlass28Layout.setHorizontalGroup(
            panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTotalSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass28Layout.setVerticalGroup(
            panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTotalSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass18Layout = new javax.swing.GroupLayout(panelGlass18);
        panelGlass18.setLayout(panelGlass18Layout);
        panelGlass18Layout.setHorizontalGroup(
            panelGlass18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass18Layout.setVerticalGroup(
            panelGlass18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGlass28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass19.setAlpha(1.0F);
        panelGlass19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass19.setRound(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Total Pengeluaran kas");

        panelGlass34.setAlpha(1.0F);
        panelGlass34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass34.setRound(false);

        isiTotalPengeluaran.setEditable(false);
        isiTotalPengeluaran.setBorder(null);
        isiTotalPengeluaran.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiTotalPengeluaran.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiTotalPengeluaran.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        isiTotalPengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isiTotalPengeluaranKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelGlass34Layout = new javax.swing.GroupLayout(panelGlass34);
        panelGlass34.setLayout(panelGlass34Layout);
        panelGlass34Layout.setHorizontalGroup(
            panelGlass34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTotalPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass34Layout.setVerticalGroup(
            panelGlass34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTotalPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass19Layout = new javax.swing.GroupLayout(panelGlass19);
        panelGlass19.setLayout(panelGlass19Layout);
        panelGlass19Layout.setHorizontalGroup(
            panelGlass19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass19Layout.setVerticalGroup(
            panelGlass19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlass34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass21.setAlpha(1.0F);
        panelGlass21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass21.setRound(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Setoran Tunai");

        panelGlass38.setAlpha(1.0F);
        panelGlass38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass38.setRound(false);

        isiSetoran.setBorder(null);
        isiSetoran.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiSetoran.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiSetoran.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass38Layout = new javax.swing.GroupLayout(panelGlass38);
        panelGlass38.setLayout(panelGlass38Layout);
        panelGlass38Layout.setHorizontalGroup(
            panelGlass38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiSetoran, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass38Layout.setVerticalGroup(
            panelGlass38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiSetoran, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass21Layout = new javax.swing.GroupLayout(panelGlass21);
        panelGlass21.setLayout(panelGlass21Layout);
        panelGlass21Layout.setHorizontalGroup(
            panelGlass21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass21Layout.setVerticalGroup(
            panelGlass21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGlass38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass3.setAlpha(0.0F);
        panelGlass3.setRound(false);

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_submit.png"))); // NOI18N
        btnSubmit.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnSubmit.setOpaque(true);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_refresh.png"))); // NOI18N
        btnRefresh.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(117, 41));
        btnRefresh.setRoundRect(true);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(204, 0, 51));
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Printer.png"))); // NOI18N
        btnPrint.setFont(new java.awt.Font("Meiryo", 0, 14)); // NOI18N
        btnPrint.setOpaque(true);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelGlass22.setAlpha(1.0F);
        panelGlass22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass22.setRound(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Sisa Pemasukan");

        panelGlass35.setAlpha(1.0F);
        panelGlass35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass35.setRound(false);

        isiSisaPemasukan.setBorder(null);
        isiSisaPemasukan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiSisaPemasukan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiSisaPemasukan.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        isiSisaPemasukan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isiSisaPemasukanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelGlass35Layout = new javax.swing.GroupLayout(panelGlass35);
        panelGlass35.setLayout(panelGlass35Layout);
        panelGlass35Layout.setHorizontalGroup(
            panelGlass35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass35Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiSisaPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass35Layout.setVerticalGroup(
            panelGlass35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiSisaPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass22Layout = new javax.swing.GroupLayout(panelGlass22);
        panelGlass22.setLayout(panelGlass22Layout);
        panelGlass22Layout.setHorizontalGroup(
            panelGlass22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass22Layout.setVerticalGroup(
            panelGlass22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGlass35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass23.setAlpha(1.0F);
        panelGlass23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass23.setRound(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Saldo Esok Hari");

        panelGlass39.setAlpha(1.0F);
        panelGlass39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass39.setRound(false);

        isiSaldoEsok.setBorder(null);
        isiSaldoEsok.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiSaldoEsok.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiSaldoEsok.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass39Layout = new javax.swing.GroupLayout(panelGlass39);
        panelGlass39.setLayout(panelGlass39Layout);
        panelGlass39Layout.setHorizontalGroup(
            panelGlass39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass39Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiSaldoEsok, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass39Layout.setVerticalGroup(
            panelGlass39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiSaldoEsok, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass23Layout = new javax.swing.GroupLayout(panelGlass23);
        panelGlass23.setLayout(panelGlass23Layout);
        panelGlass23Layout.setHorizontalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass23Layout.setVerticalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGlass39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGlass26.setAlpha(1.0F);
        panelGlass26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass26.setRound(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Total Pemasukan");

        panelGlass40.setAlpha(1.0F);
        panelGlass40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass40.setRound(false);

        isiTotalPemasukan.setEditable(false);
        isiTotalPemasukan.setBorder(null);
        isiTotalPemasukan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiTotalPemasukan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isiTotalPemasukan.setFont(new java.awt.Font("Meiryo UI", 1, 12)); // NOI18N
        isiTotalPemasukan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                isiTotalPemasukanKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelGlass40Layout = new javax.swing.GroupLayout(panelGlass40);
        panelGlass40.setLayout(panelGlass40Layout);
        panelGlass40Layout.setHorizontalGroup(
            panelGlass40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass40Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTotalPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass40Layout.setVerticalGroup(
            panelGlass40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTotalPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass26Layout = new javax.swing.GroupLayout(panelGlass26);
        panelGlass26.setLayout(panelGlass26Layout);
        panelGlass26Layout.setHorizontalGroup(
            panelGlass26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass26Layout.setVerticalGroup(
            panelGlass26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelGlass40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGlass15Layout = new javax.swing.GroupLayout(panelGlass15);
        panelGlass15.setLayout(panelGlass15Layout);
        panelGlass15Layout.setHorizontalGroup(
            panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass15Layout.createSequentialGroup()
                .addGroup(panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass15Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelGlass8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelGlass26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelGlass15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass15Layout.setVerticalGroup(
            panelGlass15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass15Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panelGlass18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        proArus.add(panelGlass15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 587, 530));

        panelGjam.setBackground(new java.awt.Color(102, 102, 102));
        panelGjam.setOpaque(true);
        panelGjam.setRound(false);

        tglVw.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tglVw.setForeground(new java.awt.Color(255, 255, 255));
        tglVw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tglVw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        javax.swing.GroupLayout panelGjamLayout = new javax.swing.GroupLayout(panelGjam);
        panelGjam.setLayout(panelGjamLayout);
        panelGjamLayout.setHorizontalGroup(
            panelGjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGjamLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panelGjamLayout.setVerticalGroup(
            panelGjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGjamLayout.createSequentialGroup()
                .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        proArus.add(panelGjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, -1, -1));

        errmsg.setRound(false);

        lblPesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPesan.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout errmsgLayout = new javax.swing.GroupLayout(errmsg);
        errmsg.setLayout(errmsgLayout);
        errmsgLayout.setHorizontalGroup(
            errmsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errmsgLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        errmsgLayout.setVerticalGroup(
            errmsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPesan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        proArus.add(errmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(proArus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(proArus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void isiTotalSaldoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiTotalSaldoKeyReleased
        // TODO add your handling code here:
        mat();
    }//GEN-LAST:event_isiTotalSaldoKeyReleased

    private void isiTotalPengeluaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiTotalPengeluaranKeyReleased
        // TODO add your handling code here:
        mat();
    }//GEN-LAST:event_isiTotalPengeluaranKeyReleased

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(idV==null){
            if(!isiSetoran.getText().isEmpty()){
                addAruskas();
                InsertSaldo p = new InsertSaldo();
                p.setVisible(true);
                p.callUser(setIdUser);
            }else{
                JOptionPane.showMessageDialog(this, "Setoran Tunai Kosong");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Proyeksi untuk Hari Ini Sudah Diisi");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        focus();
        clear();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void isiSisaPemasukanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiSisaPemasukanKeyReleased
        // TODO add your handling code here:
        mat();
    }//GEN-LAST:event_isiSisaPemasukanKeyReleased

    private void isiTotalPemasukanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiTotalPemasukanKeyReleased
        // TODO add your handling code here:
        mat();
    }//GEN-LAST:event_isiTotalPemasukanKeyReleased

    private void isiTotalPendapatanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiTotalPendapatanKeyReleased
        // TODO add your handling code here:
        mat();
    }//GEN-LAST:event_isiTotalPendapatanKeyReleased

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
         cetPr.CetParm("/laporan/Proyeksi.jrxml",tglVw);
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.widget.ButtonGlass btnPrint;
    private usu.widget.ButtonGlass btnRefresh;
    private usu.widget.ButtonGlass btnSubmit;
    private usu.widget.glass.PanelGlass errmsg;
    private javax.swing.JFormattedTextField isiBankA;
    private javax.swing.JFormattedTextField isiBankB;
    private javax.swing.JFormattedTextField isiBankC;
    private javax.swing.JFormattedTextField isiCash;
    private javax.swing.JFormattedTextField isiSaldoEsok;
    private javax.swing.JFormattedTextField isiSetoran;
    private javax.swing.JFormattedTextField isiSisaPemasukan;
    private javax.swing.JFormattedTextField isiTotalPemasukan;
    private javax.swing.JFormattedTextField isiTotalPendapatan1;
    private javax.swing.JFormattedTextField isiTotalPengeluaran;
    private javax.swing.JFormattedTextField isiTotalSaldo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private usu.widget.Label lblPesan;
    private usu.widget.glass.PanelGlass panelGjam;
    private usu.widget.glass.PanelGlass panelGlass15;
    private usu.widget.glass.PanelGlass panelGlass18;
    private usu.widget.glass.PanelGlass panelGlass19;
    private usu.widget.glass.PanelGlass panelGlass21;
    private usu.widget.glass.PanelGlass panelGlass22;
    private usu.widget.glass.PanelGlass panelGlass23;
    private usu.widget.glass.PanelGlass panelGlass25;
    private usu.widget.glass.PanelGlass panelGlass26;
    private usu.widget.glass.PanelGlass panelGlass28;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass30;
    private usu.widget.glass.PanelGlass panelGlass31;
    private usu.widget.glass.PanelGlass panelGlass32;
    private usu.widget.glass.PanelGlass panelGlass33;
    private usu.widget.glass.PanelGlass panelGlass34;
    private usu.widget.glass.PanelGlass panelGlass35;
    private usu.widget.glass.PanelGlass panelGlass36;
    private usu.widget.glass.PanelGlass panelGlass38;
    private usu.widget.glass.PanelGlass panelGlass39;
    private usu.widget.glass.PanelGlass panelGlass40;
    private usu.widget.glass.PanelGlass panelGlass8;
    private javax.swing.JPanel proArus;
    private javax.swing.JLabel tglVw;
    // End of variables declaration//GEN-END:variables

    public void clear(){
        isiSaldoEsok.setText("");
        isiSetoran.setText("");
        isiSisaPemasukan.setText("");
        isiTotalPemasukan.setText("");
        isiTotalPendapatan1.setText("");
        isiTotalPengeluaran.setText("");
        isiTotalSaldo.setText("");
        isiBankA.setText("");
        isiBankB.setText("");
        isiBankC.setText("");
        isiCash.setText("");
    }
    
    
    private void load(){
        salQue.viewTotalSaldo(tglVw, isiTotalSaldo);
        subtQue.sumAll(tglVw, isiTotalPendapatan1);
        pengQue.viewTotalPengeluaran(tglVw, isiTotalPengeluaran);
        subtQue.sumTransaksi(tglVw, isiCash);
        subtQue.sumBankA(tglVw, isiBankA);
        subtQue.sumBankB(tglVw, isiBankB);
        subtQue.sumBankC(tglVw, isiBankC);
        
    }
    
    private void loadTabel(){
        List<String[]> result = arusQue.viewArusKas(tglVw);
        String tglPembelian;
        //tglPembelian = tglVw.getText().trim();

        for(int i = 0; i < result.size();i++){
            String[] r = result.get(i);
            idV=r[0];
            isiTotalSaldo.setText(r[2]);
            isiTotalPendapatan1.setText(r[3]);
            isiCash.setText(r[4]);
            isiBankA.setText(r[5]);
            isiBankB.setText(r[6]);
            isiBankC.setText(r[7]);
            isiTotalPemasukan.setText(r[8]);
            isiTotalPengeluaran.setText(r[9]);
            isiSisaPemasukan.setText(r[10]);
            isiSetoran.setText(r[11]);
            isiSaldoEsok.setText(r[12]);
        }
       // clear();
    }
    
    private void mat(){
        String isiTtlSld = String.valueOf(isiTotalSaldo.getValue());
        BigDecimal ttlsld = new BigDecimal(isiTtlSld);
        String isiTtlPeng = String.valueOf(isiTotalPengeluaran.getValue());
        BigDecimal ttlpeng = new BigDecimal(isiTtlPeng);
        String isiTtlPend = String.valueOf(isiTotalPendapatan1.getValue());
        BigDecimal ttlpend = new BigDecimal(isiTtlPend);
        
        BigDecimal yyy = ttlsld.add(ttlpend);
        isiTotalPemasukan.setValue(yyy);
        
        if( ttlpeng.compareTo(ttlsld) < 0){//ttlsld>ttlpeng
                BigDecimal zzz = ttlsld.subtract(ttlpeng);
                isiSaldoEsok.setValue(zzz);
                isiSisaPemasukan.setText(isiTtlPend);
        }else{
                //BigDecimal yyy = ttlsld.add(ttlpend);
                BigDecimal zzz = yyy.subtract(ttlpeng);
                isiSisaPemasukan.setValue(zzz);
        }
        
    }
    
    public void addAruskas(){
        try{
            insertSave();
            lblPesan.setText(" Berhasil ditambahkan! ");
            lblPesan.setForeground(Color.green);
        }catch(Exception e){
            lblPesan.setText(" Gagal ditambahkan! ");
            lblPesan.setForeground(Color.red);
        }  
        
    }
    
    public void insertSave(){

        arusQue.insertInto(tglVw,isiTotalSaldo,isiTotalPendapatan1,isiTotalPemasukan,isiTotalPengeluaran,
        isiSisaPemasukan,isiSetoran,isiSaldoEsok,isiCash,isiBankA,isiBankB,isiBankC);
        clear();
    }

    private void focus(){
        proArus.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                isiTotalSaldo.requestFocusInWindow();
                isiTotalPengeluaran.requestFocusInWindow();
                isiTotalPendapatan1.requestFocusInWindow();
                isiTotalPemasukan.requestFocusInWindow();
                isiSetoran.requestFocusInWindow();
                isiSisaPemasukan.requestFocusInWindow();
                isiSaldoEsok.requestFocusInWindow();
                isiBankC.requestFocusInWindow();
                isiCash.requestFocusInWindow();
                isiBankB.requestFocusInWindow();
                isiBankA.requestFocusInWindow();
                loadTabel();
                if (idV==null){
                    clear();
                    load();
                    saveNlC();
                }
            }
        });
     }
    
    public void saveNlC(){
        if(isiCash.getText().isEmpty()){
            if(isiBankA.getText().isEmpty()){
                if(isiBankB.getText().isEmpty()){
                    if(isiBankC.getText().isEmpty()){
                        isiCash.setText("0");
                        isiBankA.setText("0");
                        isiBankB.setText("0");
                        isiBankC.setText("0");
                    }else{
                        isiCash.setText("0");
                        isiBankA.setText("0");
                        isiBankB.setText("0");
                    }
                }else{
                    isiCash.setText("0");
                    isiBankA.setText("0");
                }
            }else{
                isiCash.setText("0");
            }
        }else{
            if(isiBankA.getText().isEmpty()){
                if(isiBankB.getText().isEmpty()){
                    if(isiBankC.getText().isEmpty()){
                        isiBankA.setText("0");
                        isiBankB.setText("0");
                        isiBankC.setText("0");
                    }else{
                        isiBankA.setText("0");
                        isiBankB.setText("0");
                    }
                }else{
                    isiBankA.setText("0");
                    isiBankC.setText("0");
                }
            }else{
                if(isiBankB.getText().isEmpty()){
                    if(isiBankC.getText().isEmpty()){
                        isiBankB.setText("0");
                        isiBankC.setText("0");
                    }else{
                        isiBankB.setText("0");
                    }
                }else{
                    if(isiBankC.getText().isEmpty()){
                        isiBankC.setText("0");
                    }
                }
            }
        }
    }

}
