/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.aruskas;

import com.service.*;
import com.query.*;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Point;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ARCH
 */
public class SaldoPems extends javax.swing.JPanel {
GridBagLayout layout = new GridBagLayout();

PemsSaldoQuery pemdoQue;
SaldoQuery saldoQue;
PembelianQuery pembQue;
PemasukanQuery pemQue;
SaldoService saldoServ;

DefaultTableModel model;
java.util.Date tglSekarang = new java.util.Date();
    String setUser,setIdUser;
    private SimpleDateFormat smpdt = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
    private String tanggal = smpdt.format(tglSekarang);

    /**
     * Creates new form pembukuanMasuk
     */
    public SaldoPems(String Id) {
        initComponents();
          //construct query
        setIdUser = Id;
        tglVw.setText(tanggal);
        pemdoQue = new PemsSaldoQuery();
        saldoQue = new SaldoQuery();
        pemQue = new PemasukanQuery();
        model = new DefaultTableModel();
        //BynganNom.setText("0");

       //contruct metode matematika
        saldoServ = new SaldoService();
        //contruct tanggal
        tglVw.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        panelGJam.setVisible(false);
        //panelBayangan.setVisible(false);
        String Bay;
       // c.gridx = 0;
        //c.gridy = 0;
    
        //menampilkan data
        model.addColumn("Id");
        model.addColumn("Tanggal");
        model.addColumn("Nama Petugas");
        model.addColumn("Saldo Tambahan");
        model.addColumn("Status Saldo");
        model.addColumn("Keterangan");
        tabelSaldo.setModel(model);
        //focus();
        loadTabel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        err_msg1 = new usu.widget.glass.PanelGlass();
        err_msg = new usu.widget.Label();
        panelGlass16 = new usu.widget.glass.PanelGlass();
        panelGlass10 = new usu.widget.glass.PanelGlass();
        isiKeterangan = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        panelGlass22 = new usu.widget.glass.PanelGlass();
        panelGlass25 = new usu.widget.glass.PanelGlass();
        isiSaldo = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        panelGlass24 = new usu.widget.glass.PanelGlass();
        panelGlass26 = new usu.widget.glass.PanelGlass();
        ketSal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        panelGlass23 = new usu.widget.glass.PanelGlass();
        panelGlass27 = new usu.widget.glass.PanelGlass();
        isiTotalSaldo = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        panelGlass28 = new usu.widget.glass.PanelGlass();
        panelGlass29 = new usu.widget.glass.PanelGlass();
        isiTtlPemasukan = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        btnDel = new usu.widget.ButtonGlass();
        btnEdit = new usu.widget.ButtonGlass();
        btnAdd = new usu.widget.ButtonGlass();
        btnRefresh = new usu.widget.ButtonGlass();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSaldo = new javax.swing.JTable();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        btnSearch1 = new usu.widget.ButtonGlass();
        txtSearch = new javax.swing.JTextField();
        idV = new javax.swing.JTextField();
        Bay = new javax.swing.JFormattedTextField();
        panelGJam = new usu.widget.glass.PanelGlass();
        tglVw = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 73, 154));
        setMinimumSize(new java.awt.Dimension(1366, 590));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1366, 590));

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 590));

        err_msg1.setRound(false);

        err_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        err_msg.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout err_msg1Layout = new javax.swing.GroupLayout(err_msg1);
        err_msg1.setLayout(err_msg1Layout);
        err_msg1Layout.setHorizontalGroup(
            err_msg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(err_msg1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(err_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        err_msg1Layout.setVerticalGroup(
            err_msg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(err_msg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        panelGlass16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass16.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass16.setRound(false);

        panelGlass10.setAlpha(1.0F);
        panelGlass10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass10.setRound(false);

        isiKeterangan.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        isiKeterangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "saldo tambahan", "saldo usaha tambahan", "saldo usaha" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Status");

        javax.swing.GroupLayout panelGlass10Layout = new javax.swing.GroupLayout(panelGlass10);
        panelGlass10.setLayout(panelGlass10Layout);
        panelGlass10Layout.setHorizontalGroup(
            panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass10Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isiKeterangan, 0, 280, Short.MAX_VALUE))
        );
        panelGlass10Layout.setVerticalGroup(
            panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelGlass10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isiKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelGlass22.setAlpha(1.0F);
        panelGlass22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass22.setRound(false);

        panelGlass25.setAlpha(1.0F);
        panelGlass25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass25.setRound(false);

        isiSaldo.setBorder(null);
        isiSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiSaldo.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelGlass25Layout = new javax.swing.GroupLayout(panelGlass25);
        panelGlass25.setLayout(panelGlass25Layout);
        panelGlass25Layout.setHorizontalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass25Layout.setVerticalGroup(
            panelGlass25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Nominal");

        javax.swing.GroupLayout panelGlass22Layout = new javax.swing.GroupLayout(panelGlass22);
        panelGlass22.setLayout(panelGlass22Layout);
        panelGlass22Layout.setHorizontalGroup(
            panelGlass22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass22Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass22Layout.setVerticalGroup(
            panelGlass22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass22Layout.createSequentialGroup()
                .addGroup(panelGlass22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass24.setAlpha(1.0F);
        panelGlass24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass24.setRound(false);

        panelGlass26.setAlpha(1.0F);
        panelGlass26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass26.setRound(false);

        ketSal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ketSal.setBorder(null);

        javax.swing.GroupLayout panelGlass26Layout = new javax.swing.GroupLayout(panelGlass26);
        panelGlass26.setLayout(panelGlass26Layout);
        panelGlass26Layout.setHorizontalGroup(
            panelGlass26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ketSal)
                .addContainerGap())
        );
        panelGlass26Layout.setVerticalGroup(
            panelGlass26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ketSal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Keterangan");

        javax.swing.GroupLayout panelGlass24Layout = new javax.swing.GroupLayout(panelGlass24);
        panelGlass24.setLayout(panelGlass24Layout);
        panelGlass24Layout.setHorizontalGroup(
            panelGlass24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass24Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass24Layout.setVerticalGroup(
            panelGlass24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass24Layout.createSequentialGroup()
                .addGroup(panelGlass24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGlass16Layout = new javax.swing.GroupLayout(panelGlass16);
        panelGlass16.setLayout(panelGlass16Layout);
        panelGlass16Layout.setHorizontalGroup(
            panelGlass16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGlass16Layout.setVerticalGroup(
            panelGlass16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGlass24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        panelGlass5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        panelGlass5.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass5.setRound(false);

        panelGlass23.setAlpha(1.0F);
        panelGlass23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass23.setRound(false);

        panelGlass27.setAlpha(1.0F);
        panelGlass27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass27.setRound(false);

        isiTotalSaldo.setEditable(false);
        isiTotalSaldo.setBackground(new java.awt.Color(255, 255, 255));
        isiTotalSaldo.setBorder(null);
        isiTotalSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        isiTotalSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiTotalSaldo.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        isiTotalSaldo.setOpaque(false);

        javax.swing.GroupLayout panelGlass27Layout = new javax.swing.GroupLayout(panelGlass27);
        panelGlass27.setLayout(panelGlass27Layout);
        panelGlass27Layout.setHorizontalGroup(
            panelGlass27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTotalSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass27Layout.setVerticalGroup(
            panelGlass27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTotalSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Total Saldo");

        javax.swing.GroupLayout panelGlass23Layout = new javax.swing.GroupLayout(panelGlass23);
        panelGlass23.setLayout(panelGlass23Layout);
        panelGlass23Layout.setHorizontalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass23Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass23Layout.setVerticalGroup(
            panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass23Layout.createSequentialGroup()
                .addGroup(panelGlass23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelGlass28.setAlpha(1.0F);
        panelGlass28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass28.setRound(false);

        panelGlass29.setAlpha(1.0F);
        panelGlass29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGlass29.setRound(false);

        isiTtlPemasukan.setEditable(false);
        isiTtlPemasukan.setBorder(null);
        isiTtlPemasukan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        isiTtlPemasukan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        isiTtlPemasukan.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        isiTtlPemasukan.setOpaque(false);

        javax.swing.GroupLayout panelGlass29Layout = new javax.swing.GroupLayout(panelGlass29);
        panelGlass29.setLayout(panelGlass29Layout);
        panelGlass29Layout.setHorizontalGroup(
            panelGlass29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isiTtlPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass29Layout.setVerticalGroup(
            panelGlass29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(isiTtlPemasukan, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Total Pemasukan");

        javax.swing.GroupLayout panelGlass28Layout = new javax.swing.GroupLayout(panelGlass28);
        panelGlass28.setLayout(panelGlass28Layout);
        panelGlass28Layout.setHorizontalGroup(
            panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass28Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass28Layout.setVerticalGroup(
            panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass28Layout.createSequentialGroup()
                .addGroup(panelGlass28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGlass29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGlass5Layout = new javax.swing.GroupLayout(panelGlass5);
        panelGlass5.setLayout(panelGlass5Layout);
        panelGlass5Layout.setHorizontalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelGlass23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGlass28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelGlass5Layout.setVerticalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelGlass28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        panelGlass3.setAlpha(0.0F);
        panelGlass3.setRound(false);

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_delete.png"))); // NOI18N
        btnDel.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnDel.setPreferredSize(new java.awt.Dimension(117, 41));
        btnDel.setRoundRect(true);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_edit.png"))); // NOI18N
        btnEdit.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnEdit.setPreferredSize(new java.awt.Dimension(117, 41));
        btnEdit.setRoundRect(true);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_new.png"))); // NOI18N
        btnAdd.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnAdd.setRoundRect(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/doc_refresh.png"))); // NOI18N
        btnRefresh.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(117, 41));
        btnRefresh.setRoundRect(true);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tabelSaldo.setAutoCreateRowSorter(true);
        tabelSaldo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Saldo", "Nominal Saldo", "Keterangan"
            }
        ));
        tabelSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSaldoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSaldo);

        panelGlass4.setAlpha(1.0F);
        panelGlass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panelGlass4.setRound(false);

        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/btn_search.png"))); // NOI18N
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelGlass4Layout = new javax.swing.GroupLayout(panelGlass4);
        panelGlass4.setLayout(panelGlass4Layout);
        panelGlass4Layout.setHorizontalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass4Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGlass4Layout.setVerticalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSearch1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        idV.setBackground(new java.awt.Color(0, 153, 204));
        idV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idV.setForeground(new java.awt.Color(51, 51, 51));
        idV.setBorder(null);
        idV.setOpaque(false);

        Bay.setBackground(new java.awt.Color(0, 153, 204));
        Bay.setBorder(null);
        Bay.setForeground(new java.awt.Color(51, 51, 51));
        Bay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        Bay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Bay.setFont(new java.awt.Font("Meiryo UI", 0, 12)); // NOI18N
        Bay.setOpaque(false);

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(idV, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bay, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelGlass4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Bay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );

        panelGJam.setBackground(new java.awt.Color(102, 102, 102));
        panelGJam.setOpaque(true);
        panelGJam.setRound(false);

        tglVw.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tglVw.setForeground(new java.awt.Color(255, 255, 255));
        tglVw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tglVw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        javax.swing.GroupLayout panelGJamLayout = new javax.swing.GroupLayout(panelGJam);
        panelGJam.setLayout(panelGJamLayout);
        panelGJamLayout.setHorizontalGroup(
            panelGJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGJamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelGJamLayout.setVerticalGroup(
            panelGJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGJamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglVw, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(err_msg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(panelGlass16, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelGlass5, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(229, 229, 229)
                .addComponent(panelGJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(err_msg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelGlass16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelGlass5, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(panelGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadTabel();
        clear();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tabelSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSaldoMouseClicked
        // TODO add your handling code here:
       tabelMouseAction();
        //        MatSaldo();
    }//GEN-LAST:event_tabelSaldoMouseClicked

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        //        // TODO add your handling code here:
                ssearchAction();
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
                ssearchAction();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addAction();
        //loadTabel();
//        clear();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

               // loadTabel();
                editAction();
        //        upteSaldo();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
               // loadTabel();
                delAction();
        //        upteSaldo();
    }//GEN-LAST:event_btnDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Bay;
    private usu.widget.ButtonGlass btnAdd;
    private usu.widget.ButtonGlass btnDel;
    private usu.widget.ButtonGlass btnEdit;
    private usu.widget.ButtonGlass btnRefresh;
    private usu.widget.ButtonGlass btnSearch1;
    private usu.widget.Label err_msg;
    private usu.widget.glass.PanelGlass err_msg1;
    private javax.swing.JTextField idV;
    private javax.swing.JComboBox isiKeterangan;
    private javax.swing.JFormattedTextField isiSaldo;
    private javax.swing.JFormattedTextField isiTotalSaldo;
    private javax.swing.JFormattedTextField isiTtlPemasukan;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ketSal;
    private usu.widget.glass.PanelGlass panelGJam;
    private usu.widget.glass.PanelGlass panelGlass10;
    private usu.widget.glass.PanelGlass panelGlass16;
    private usu.widget.glass.PanelGlass panelGlass22;
    private usu.widget.glass.PanelGlass panelGlass23;
    private usu.widget.glass.PanelGlass panelGlass24;
    private usu.widget.glass.PanelGlass panelGlass25;
    private usu.widget.glass.PanelGlass panelGlass26;
    private usu.widget.glass.PanelGlass panelGlass27;
    private usu.widget.glass.PanelGlass panelGlass28;
    private usu.widget.glass.PanelGlass panelGlass29;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private javax.swing.JTable tabelSaldo;
    private javax.swing.JLabel tglVw;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

   
    
    
    public void clear(){
        //err_msg.setText("");
        isiSaldo.setText("");
        Bay.setText("");
        idV.setText("");
        isiKeterangan.setEnabled(true);
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDel.setEnabled(true);
    } 
    
    private void loadTabel(){
        isiTotalSaldo.setFocusable(true);
        List<String[]> result = pemdoQue.viewSaldoTambahan(tglVw);
        String TGL_SALDO;
        TGL_SALDO = tglVw.getText().trim();
        saldoQue.viewTotalSaldo(tglVw,isiTotalSaldo);
        pemQue.viewTotalPemasukan(tglVw,isiTtlPemasukan);/// TANDA TANYA KETIKA PROYEKSI ARUSKAS <OK ATAU BELUM>
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        tabelSaldo.setModel(model);
        for(int i = 0; i < result.size();i++){
            model.addRow(result.get(i));
        }
        tabelSaldo.repaint();
        model.fireTableDataChanged();
        focus();
        clear();
    }
    
    private void addAction() {
        /**sebelum melakukan add
         * kondisikan memilih input dan keterangan
        */ 
        if(isiSaldo.getText().isEmpty()){
            if(isiTotalSaldo.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Isikan Nominal Saldo!! Saldo Hari ini Kosong");
            } else{
                JOptionPane.showMessageDialog(this, "Isikan Nominal Saldo");
            }
        } else{
            String isiSldo = String.valueOf(isiSaldo.getValue());
            BigDecimal isiSld = new BigDecimal(isiSldo);
            if(isiSld.compareTo(BigDecimal.ZERO)>0){
                String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
                    BigDecimal nomTtlSldo = new BigDecimal(isiTtlSaldo);
                if(!isiTotalSaldo.getText().isEmpty()){
                    if(nomTtlSldo.equals(BigDecimal.ZERO)){
                        if(JOptionPane.showConfirmDialog(this, "Masukkan Saldo dulu!!", "Peringatan", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION){
                           MatEdit();
                        }
                    }else{
                        if(isiKeterangan.getSelectedItem()!= "saldo tambahan"&&isiKeterangan.getSelectedItem()!= "saldo usaha tambahan"){//harus sama persis
                            JOptionPane.showMessageDialog(this, " Ganti Status Saldo 'Saldo Tambahan' atau 'Saldo Usaha Tambahan'!! ");
                        }else{
                            try{
                                //prodQue.insertInto(tglVw,isiSaldo,isiKeterangan);
                                 MatEdit();
                                //System.out.println(""+isiTotalSaldo.getText());
                                err_msg.setText(" Berhasil ditambahkan! ");
                                err_msg.setForeground(Color.green);
                            }
                            catch(Exception e){
                                err_msg.setText(" Gagal ditambahkan! ");
                                err_msg.setForeground(Color.red);
                            }  
                        }
                    }
                }else {///fix gak usah pakai hitungan tambah untuk SALDO TAMBAHAN
                    if(isiKeterangan.getSelectedItem()== "saldo tambahan"||isiKeterangan.getSelectedItem()== "saldo usaha tambahan"){
                        JOptionPane.showMessageDialog(this, "Ganti Status Saldo 'Saldo Usaha'!!");
                    } else if (isiKeterangan.getSelectedItem()== "saldo usaha"){
                        try{
                            insertMat();
                            err_msg.setText(" Berhasil ditambahkan! ");
                            err_msg.setForeground(Color.green);
                        }
                        catch(Exception e){
                        err_msg.setText(" Gagal ditambahkan! ");
                        err_msg.setForeground(Color.red);
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, " jangan Gunakan 0 ");
                isiSaldo.setText("");
            }
            loadTabel();
        }
        
    }    
    
      private void editAction() {
     //To change body of generated methods, choose Tools | Templates.
        try {
            MatEdit();
            err_msg.setText("Berhasil diedit!");
            err_msg.setForeground(Color.green);
            //JOptionPane.showMessageDialog(this,"Berhasil di Simpan");
        }
        catch(Exception ex){
        // Logger.getLogger(FInput.clatxtoperatorame()).log(Level.SEVERE, null, ex);
            err_msg.setText("Gagal diedit!");
            err_msg.setForeground(Color.red);
            //JOptionPane.showMessageDialog(this, "Maaf Gagal Simpan");
        }
        loadTabel();
    }
      
      private void delAction(){
          try{
             MatEdit();
              err_msg.setText("Berhasil diHapus!");
              err_msg.setForeground(Color.green); 
          }catch (Exception ex){
              err_msg.setText("Gagal diHapus!");
              err_msg.setForeground(Color.red);
          }
          loadTabel();
      }
    
    public void MatEdit(){
         if(Bay.getText().isEmpty()){
            String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
            BigDecimal ttlSldo = new BigDecimal(isiTtlSaldo);
            if(ttlSldo.compareTo(BigDecimal.ONE) == 0){
                isiTotalSaldo.setText("0");
                saldoServ.addMat(isiSaldo, isiTotalSaldo,isiTtlPemasukan);
            }else{
                saldoServ.addMat(isiSaldo,isiTotalSaldo,isiTtlPemasukan);
            }
            pemdoQue.insertInto(tglVw,setIdUser,isiSaldo,isiKeterangan,ketSal);
        }else{
            String isiTtlSaldo = String.valueOf(isiTotalSaldo.getValue());
            BigDecimal ttlSldo = new BigDecimal(isiTtlSaldo);
            String isiTtlpem = String.valueOf(isiTtlPemasukan.getValue());
            BigDecimal pem = new BigDecimal(isiTtlpem);
            if(ttlSldo.compareTo(BigDecimal.ZERO) > 0 && pem.compareTo(BigDecimal.ZERO)>0){
                if(!isiSaldo.getText().equals(Bay.getText())){
                    saldoServ.editMat(isiSaldo,Bay,isiTotalSaldo,isiTtlPemasukan);
                }else{
                 if(JOptionPane.showConfirmDialog(this, "Yakin menghapus data?", "Peringatan", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                        saldoServ.delMat(Bay,isiTotalSaldo,isiTtlPemasukan);
                        pemdoQue.delete(idV);
                    }
             }
              pemdoQue.edit(idV,isiSaldo);
            } else {
                JOptionPane.showMessageDialog(this, "ditambah saldo dulu");
            }
            
         }
        saldoQue.editTotalSaldoUsaha(tglVw,isiTotalSaldo);
        pemQue.editPemasukan(tglVw, isiTtlPemasukan);
    }
    
    private void tabelMouseAction() {
       //To change body of generated methods, choose Tools | Templates.
        btnAdd.setEnabled(false);
        isiKeterangan.setEnabled(false);
        int row = tabelSaldo.getSelectedRow();
        idV.setText(tabelSaldo.getModel().getValueAt(row,0).toString());
        isiSaldo.setText(tabelSaldo.getModel().getValueAt(row,3).toString());
        Bay.setText(tabelSaldo.getModel().getValueAt(row,3).toString());
        ketSal.setText(tabelSaldo.getModel().getValueAt(row,5).toString());
    }
    
    private void insertMat(){
        String NOM_SALDO = String.valueOf(isiSaldo.getValue());
        if(isiTtlPemasukan.getText().isEmpty()){
            pemQue.editPemasukan(tglVw,isiSaldo);
        }else{
             String TTL_PEM=String.valueOf(isiTtlPemasukan.getValue());
            
             BigDecimal TTLpem = new BigDecimal(TTL_PEM);
             BigDecimal nomSaldo = new BigDecimal(NOM_SALDO);
            
             BigDecimal zzz = nomSaldo.add(TTLpem);
                       
             isiTtlPemasukan.setValue(zzz);  
        }
          //  pemQue.editPemasukan(tglVw,isiTtlPemasukan);
        saldoQue.insertIntoSS(isiSaldo,tglVw);
        pemdoQue.insertInto(tglVw,setIdUser,isiSaldo,isiKeterangan,ketSal);
    }
    
     private void ssearchAction() {
       //To change body of generated methods, choose Tools | Templates.
            try{
                model.getDataVector().removeAllElements();
                model.fireTableDataChanged();
                tabelSaldo.setModel(model);
                List<String[]> result=  pemdoQue.fcSelectCommand(txtSearch);
                String search;
                search = txtSearch.getText().trim();
                for(int i = 0; i < result.size();i++){
                     model.addRow(result.get(i));
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Pencarian tidak Ditemukan!!");
            }
    }
     
     private void focus(){
        jPanel1.setVisible(true);
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                isiTotalSaldo.requestFocusInWindow();
                isiTtlPemasukan.requestFocusInWindow();
                if(isiTotalSaldo.getText().isEmpty()&& isiTtlPemasukan.getText().isEmpty()){
                    InsertSaldo p = new InsertSaldo();
                    p.setVisible(true);
                    p.callUser(setIdUser);
                }
                
            }
        });
     }

}
