/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jamtgl;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author ARCH
 */
public class Tgl extends javax.swing.JPanel {
    java.util.Date tglSekarang = new java.util.Date();
    
    private SimpleDateFormat smpdt = new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
    private String tanggal = smpdt.format(tglSekarang);
    /**
     * Creates new form Tgl
     */
    public Tgl() {
        initComponents();
        tampiltanggal.setText(tanggal);
//        ActionListener taskPerformer = new ActionListener() {
//        public void actionPerformed(ActionEvent evt) {
//        Calendar cal = new GregorianCalendar();
//        String nolTanggal = "";
//        String nolBulan = "";
//        String nolTahun = "";
//        // Membuat Date
//        Date dt = new Date();
//        // Mengambil nilaj JAM, MENIT, dan DETIK Sekarang
//      
//        int nilaiTanggal = cal.get(Calendar.DAY_OF_MONTH);
//        int nilaiBulan = cal.get(Calendar.MONTH);
//        int nilaiTahun = cal.get(Calendar.YEAR);
//        if (nilaiTanggal<10){
//            nolTanggal="0";
//        }
//        if ((nilaiBulan+1)<10){
//            nolBulan="0";
//        }
//        if (nilaiTahun<10){
//            nolTahun="0";
//        }
//        // Membuat String JAM, MENIT, DETIK
//        String tanggal = nolTanggal + Integer.toString(nilaiTanggal);
//        String bulan = nolBulan + Integer.toString(nilaiBulan+1);
//        String tahun = nolTahun + Integer.toString(nilaiTahun);
//        // Menampilkan pada Layar
//        //tampiltanggal.setText(tahun+"-"+bulan+"-"+tanggal);
//      }
//    };
}    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tampiltanggal = new javax.swing.JLabel();

        tampiltanggal.setBackground(new java.awt.Color(102, 102, 102));
        tampiltanggal.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        tampiltanggal.setForeground(new java.awt.Color(255, 255, 255));
        tampiltanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampiltanggal.setText("23-05-2015");
        tampiltanggal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white));
        tampiltanggal.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tampiltanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tampiltanggal)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tampiltanggal;
    // End of variables declaration//GEN-END:variables
}
