/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sia.ui.laporan;


import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author ARCH
 */
public class Laporan extends javax.swing.JPanel {
    GridBagLayout layout = new GridBagLayout();
    laporanAruskas ak;
    laporanPemasukan pk;
    laporanPengeluaran pa;
    laporanProduk pr;
    laporanTransaksi tr;
    
    //Panel2 p2;
    
    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        DynamicPanelpanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DynamicPanelpanel = new javax.swing.JPanel();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        label1 = new usu.widget.Label();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        LapAruskas = new usu.widget.ButtonGlass();
        lapPemasukan = new usu.widget.ButtonGlass();
        lapProduk = new usu.widget.ButtonGlass();
        lapTransaksi = new usu.widget.ButtonGlass();
        lapPengeluaran = new usu.widget.ButtonGlass();

        setBackground(java.awt.Color.darkGray);
        setPreferredSize(new java.awt.Dimension(1366, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DynamicPanelpanel.setMinimumSize(new java.awt.Dimension(1366, 633));
        DynamicPanelpanel.setOpaque(false);
        DynamicPanelpanel.setPreferredSize(new java.awt.Dimension(1366, 633));

        javax.swing.GroupLayout DynamicPanelpanelLayout = new javax.swing.GroupLayout(DynamicPanelpanel);
        DynamicPanelpanel.setLayout(DynamicPanelpanelLayout);
        DynamicPanelpanelLayout.setHorizontalGroup(
            DynamicPanelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        DynamicPanelpanelLayout.setVerticalGroup(
            DynamicPanelpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        add(DynamicPanelpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        panelGlass6.setAlpha(0.0F);
        panelGlass6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        panelGlass6.setPreferredSize(new java.awt.Dimension(264, 54));
        panelGlass6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("LAPORAN");
        label1.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        panelGlass6.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 40));

        add(panelGlass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1092, 0, -1, 40));

        panelGlass5.setAlpha(1.0F);
        panelGlass5.setPreferredSize(new java.awt.Dimension(675, 184));
        panelGlass5.setRound(false);
        panelGlass5.setToolTipText("");

        LapAruskas.setBackground(java.awt.Color.white);
        LapAruskas.setBorder(null);
        LapAruskas.setText("Laporan Arus Kas");
        LapAruskas.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        LapAruskas.setOpaque(true);
        LapAruskas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapAruskasActionPerformed(evt);
            }
        });

        lapPemasukan.setBackground(new java.awt.Color(255, 255, 255));
        lapPemasukan.setBorder(null);
        lapPemasukan.setText("Laporan Pemasukan");
        lapPemasukan.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lapPemasukan.setOpaque(true);
        lapPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapPemasukanActionPerformed(evt);
            }
        });

        lapProduk.setBackground(new java.awt.Color(255, 255, 255));
        lapProduk.setBorder(null);
        lapProduk.setText("Laporan Produk");
        lapProduk.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lapProduk.setOpaque(true);
        lapProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapProdukActionPerformed(evt);
            }
        });

        lapTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        lapTransaksi.setBorder(null);
        lapTransaksi.setText("Laporan Transaksi");
        lapTransaksi.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lapTransaksi.setOpaque(true);
        lapTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapTransaksiActionPerformed(evt);
            }
        });

        lapPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        lapPengeluaran.setBorder(null);
        lapPengeluaran.setText("Laporan Pengeluaran");
        lapPengeluaran.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lapPengeluaran.setOpaque(true);
        lapPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapPengeluaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass5Layout = new javax.swing.GroupLayout(panelGlass5);
        panelGlass5.setLayout(panelGlass5Layout);
        panelGlass5Layout.setHorizontalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addComponent(LapAruskas, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lapProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lapTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lapPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lapPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGlass5Layout.setVerticalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lapPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lapPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lapTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lapProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(LapAruskas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(panelGlass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void LapAruskasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapAruskasActionPerformed
        // TODO add your handling code here:
        DynamicPanelpanel.removeAll();
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        //adding panel
        ak = new laporanAruskas();
        DynamicPanelpanel.add(ak);
        ak.setVisible(true);
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        LapAruskas.setForeground(Color.WHITE);
        LapAruskas.setBackground(Color.DARK_GRAY);
        lapPemasukan.setForeground(Color.BLACK);
        lapPemasukan.setBackground(Color.WHITE);
        lapPengeluaran.setForeground(Color.BLACK);
        lapPengeluaran.setBackground(Color.WHITE);
        lapProduk.setForeground(Color.BLACK);
        lapProduk.setBackground(Color.WHITE);
        lapTransaksi.setForeground(Color.BLACK);
        lapTransaksi.setBackground(Color.WHITE);
    }//GEN-LAST:event_LapAruskasActionPerformed

    private void lapPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapPemasukanActionPerformed
        // TODO add your handling code here:
        DynamicPanelpanel.removeAll();
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        //adding panel
        pk = new laporanPemasukan();
        DynamicPanelpanel.add(pk);
        pk.setVisible(true);
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        LapAruskas.setForeground(Color.BLACK);
        LapAruskas.setBackground(Color.WHITE);
        lapPemasukan.setForeground(Color.WHITE);
        lapPemasukan.setBackground(Color.DARK_GRAY);
        lapPengeluaran.setForeground(Color.BLACK);
        lapPengeluaran.setBackground(Color.WHITE);
        lapProduk.setForeground(Color.BLACK);
        lapProduk.setBackground(Color.WHITE);
        lapTransaksi.setForeground(Color.BLACK);
        lapTransaksi.setBackground(Color.WHITE);
    }//GEN-LAST:event_lapPemasukanActionPerformed

    private void lapProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapProdukActionPerformed
        // TODO add your handling code here:
        DynamicPanelpanel.removeAll();
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        //adding panel
        pr = new laporanProduk();
        DynamicPanelpanel.add(pr);
        pr.setVisible(true);
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        LapAruskas.setForeground(Color.BLACK);
        LapAruskas.setBackground(Color.WHITE);
        lapPemasukan.setForeground(Color.BLACK);
        lapPemasukan.setBackground(Color.WHITE);
        lapPengeluaran.setForeground(Color.BLACK);
        lapPengeluaran.setBackground(Color.WHITE);
        lapProduk.setForeground(Color.WHITE);
        lapProduk.setBackground(Color.DARK_GRAY);
        lapTransaksi.setForeground(Color.BLACK);
        lapTransaksi.setBackground(Color.WHITE);
    }//GEN-LAST:event_lapProdukActionPerformed

    private void lapTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapTransaksiActionPerformed
        // TODO add your handling code here:
        DynamicPanelpanel.removeAll();
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        //adding panel
        tr = new laporanTransaksi();
        DynamicPanelpanel.add(tr);
        tr.setVisible(true);
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        LapAruskas.setForeground(Color.BLACK);
        LapAruskas.setBackground(Color.WHITE);
        lapPemasukan.setForeground(Color.BLACK);
        lapPemasukan.setBackground(Color.WHITE);
        lapPengeluaran.setForeground(Color.BLACK);
        lapPengeluaran.setBackground(Color.WHITE);
        lapProduk.setForeground(Color.BLACK);
        lapProduk.setBackground(Color.WHITE);
        lapTransaksi.setForeground(Color.WHITE);
        lapTransaksi.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_lapTransaksiActionPerformed

    private void lapPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapPengeluaranActionPerformed
        // TODO add your handling code here:
        DynamicPanelpanel.removeAll();
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        //adding panel
        pa = new laporanPengeluaran();
        DynamicPanelpanel.add(pa);
        pa.setVisible(true);
        DynamicPanelpanel.repaint();
        DynamicPanelpanel.revalidate();
        
        LapAruskas.setForeground(Color.BLACK);
        LapAruskas.setBackground(Color.WHITE);
        lapPemasukan.setForeground(Color.BLACK);
        lapPemasukan.setBackground(Color.WHITE);
        lapPengeluaran.setForeground(Color.WHITE);
        lapPengeluaran.setBackground(Color.DARK_GRAY);
        lapProduk.setForeground(Color.BLACK);
        lapProduk.setBackground(Color.WHITE);
        lapTransaksi.setForeground(Color.BLACK);
        lapTransaksi.setBackground(Color.WHITE);
    }//GEN-LAST:event_lapPengeluaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanelpanel;
    private usu.widget.ButtonGlass LapAruskas;
    private usu.widget.Label label1;
    private usu.widget.ButtonGlass lapPemasukan;
    private usu.widget.ButtonGlass lapPengeluaran;
    private usu.widget.ButtonGlass lapProduk;
    private usu.widget.ButtonGlass lapTransaksi;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    // End of variables declaration//GEN-END:variables
}
